### ISSUE TITLE
OIS endpoints parameters and reservedParameters are required per validator

### ISSUE THREAD

**Issue by dcroote** [api3dao/old-api3-docs#1003]
Currently [parameters](https://docs.api3.org/ois/v1.0/ois.html#_5-5-parameters) and [reservedParameters](https://docs.api3.org/ois/v1.0/ois.html#_5-4-reservedparameters) of ois.endpoints are listed as "Optional", yet the validator [requires each](https://github.com/api3dao/ois/blob/4264841d0bc366422e8d628a021ad9ef54c62aed/src/ois.ts#L272-L278).

The language currently used for `fixedOperationParameters` may be appropriate, though I'm not sure the same applies (@Siegrift  might know?):
> (Required) A list of objects specifying the fixed parameters for an API operation. While required, the fixedOperationParameters array can be left empty.

**Comment by Siegrift** [comment]
I believe these were required even with the [old validator](https://github.com/api3dao/airnode/blob/8153ef36876a8920568e376f05be5ee539d8904b/packages/validator/templates/0.1.0/ois.json#L108). I think we should just change the docs.

**Comment by dcroote** [comment]
Thanks for confirming @Siegrift. Now the only outstanding question is whether these are allowed to be empty arrays like `fixedOperationParameters`. I'll do some testing.

**Comment by Siegrift** [comment]
You need at least `_type` reserved parameters, but the parameters can be empty... E.g. the API has no parameters at all.

**Comment by dcroote** [comment]
> You need at least `_type` reserved parameters, but the parameters can be empty... E.g. the API has no parameters at all.

If I'm understanding correctly then I think we have a bug because OIS validation passes when `reservedParameters` [here](https://github.com/api3dao/ois/blob/4264841d0bc366422e8d628a021ad9ef54c62aed/test/fixtures/ois.json#L64) is set to `[]`.

To disallow an empty array we would need:
https://github.com/api3dao/ois/blob/4264841d0bc366422e8d628a021ad9ef54c62aed/src/ois.ts#L278

To be:
```ts
reservedParameters: z.array(reservedParameterSchema).nonempty()
```

**Comment by Siegrift** [comment]
Yeah, we're missing the validation for that, but what you propose is not enough. We need to check that the specified paramter is indeed `_type`

**Comment by martinkolenic** [comment]
Hi @Siegrift, as per [this thread](https://api3workspace.slack.com/archives/C02AYRX8D89/p1662455412473279), is this being retired for the time being?

**Comment by Siegrift** [comment]
It will not be part of 0.8, but will land in 0.9

**Comment by Siegrift** [comment]
Sorry, this docs change makes sense for both 0.8 and 0.9 and should be included in both.

I was specifically referring to the OIS validation ensuring this in validator will only be in 0.9.
