### ISSUE TITLE
List all airnode-examples integrations and reference functionality in relevant locations 

### ISSUE THREAD

**Issue by dcroote** [api3dao/old-api3-docs#1009]
Based on [AN-273](https://api3dao.atlassian.net/browse/AN-273) and [this thread](https://api3workspace.slack.com/archives/C02AYRX8D89/p1660799847026379), all `airnode-examples` should be listed and links to relevant `airnode-examples` integrations included where relevant.

**Comment by martinkolenic** [comment]
Hi @dcroote, this looks very good to me. From the user's perspective, this seems insanely practical as these have been next to invisible, really. Big kudos!
