### ISSUE TITLE
Docs: Publish Airnode v0.8

### ISSUE THREAD

**Issue by dcroote** [api3dao/old-api3-docs#1015]
Since Airnode v0.8.0 is now released: https://github.com/api3dao/airnode/issues/1421

**Comment by dcroote** [comment]
This should also update the default OIS docs version to `v1.1` per https://github.com/api3dao/api3-docs/issues/869

**Comment by martinkolenic** [comment]
The docs are up and running and opening the Airnode section from `docs.api3.org` defaults to v0.8, as it should. Searching the docset works well, too.
