### ISSUE TITLE
Update OIS version dependency table

### ISSUE THREAD

**Issue by wkande** [api3dao/old-api3-docs#1028]
This table is currently a Vue component. I think it should be changed back to a markdown table. Doing so requires a small change to both OIS `1.0.0` and `1.1.1`.

[Here](https://docs.api3.org/ois/v1.1/#releases)

**Comment by wkande** [comment]
Decided to update the dependency chart in `ois-AirnodeOisVersions.vue` component and changed the `/dev/release-notes.md` page instructions to update `ois-AirnodeOisVersions.vue` when a new Airnode released.

- http://docs.api3.org/ois/v1.1/#releases
- http://docs.api3.org/dev/release-notes.html

**Comment by dcroote** [comment]
Nice! Closed by #1033
