### ISSUE TITLE
Remove remnants of Rinkeby and Ropsten networks

### ISSUE THREAD

**Issue by amarthadan** [api3dao/old-api3-docs#1032]
Documentation for https://github.com/api3dao/airnode/issues/1280

**Comment by wkande** [comment]
As noted in the PR, do we want to do this for Airnode `v0.9` as well?

**Comment by Siegrift** [comment]
Yes. I'll make the changes to the 0.9 docsets as well (in the linked PR)

**Comment by wkande** [comment]
I believe this might benefit from testing the tutorials after the `v0.9` docker image is released. Do not know if we want to move it to blocked or not.
