### ISSUE TITLE
Add an example of using off-chain `authorizations` in `config.json`

### ISSUE THREAD

**Issue by vponline** [api3dao/old-api3-docs#1044]
An example of how to use `authorizations` to docs (into `authorization.md`, to be added to versions since `0.8`),

 For example in the form of:

If you wanted to authorize address `0xabc...` for endpoint `0x123...`, you'd set it as:

```
authorizations: {
    requesterEndpointAuthorizations: {
      '0x123...': ['0xabc...'],
    },
  }
```

**Comment by wkande** [comment]
@vponline 
I was thinking that we might want to create a new page for this under "**Concepts and Definitions**". Maybe titled **Authorizations**? I had renamed `authorization.md` to `authorizers.md` in #1045 to allow for this. What do you think? This way we can do a full write up on Authorizations.

Also why is `requesterEndpointAuthorizations` an object in your example from above, as shown below?

```
authorizations: {
    requesterEndpointAuthorizations: {
      '0x123...': ['0xabc...'],
    },
  }
```

Also after this gets done I plan to follow-up and add Authorizations into **Build and Airnode** `apply-auth.md`. It would need a title change but that is minor.

**Comment by vponline** [comment]
> I was thinking that we might want to create a new page for this under "Concepts and Definitions". Maybe titled Authorizations?

I think this is a great idea especially since there will be different types of authorization/authorizer options to choose from so a dedicated section makes sense.

> I had renamed authorization.md to authorizers.md in https://github.com/api3dao/api3-docs/issues/1045 to allow for this. What do you think? This way we can do a full write up on Authorizations.

I agree that they can be in the same file since they are so closely related (the big distinction being one is for on-chain and the other for off-chain authorization).

> Also why is `requesterEndpointAuthorizations` an object in your example from above, as shown below?

It is an object because the authorizations are defined at the endpoint level (so the key for the object is an `endpointId`) and the value is the array of authorized requester addresses for that specific endpoint.

**Comment by wkande** [comment]
> I agree that they can be in the same file since they are so closely related (the big distinction being one is for on-chain and the other for off-chain authorization).

Actually I was thinking we would have two files under **Concepts and Definitions**: `authorizers.md` and `authorizations.md`.

**Comment by vponline** [comment]
> Actually I was thinking we would have two files under Concepts and Definitions: authorizers.md and authorizations.md.

Ok I don't see any problem with that and shorter pages are probably nicer for readers anyway.

**Comment by dcroote** [comment]
Closing as the two separate pages are live in the docs and this is marked Done.
