### ISSUE TITLE
Bump OIS to 1.2.0

### ISSUE THREAD

**Issue by amarthadan** [api3dao/old-api3-docs#1051]
Documentation for https://github.com/api3dao/airnode/issues/1465

**Comment by dcroote** [comment]
@wkande  for this we need Airnode `v0.9` and `v0.10` to point to a new `v1.2` OIS doc set

**Comment by wkande** [comment]
@dcroote - I thought Airnode `v0.9` was using OIS `v1.1.2` and Airnode `v0.10` was moving to OIS `v1.2`? If not was is the purpose of OIS `v1.2.0`?

Updated this comment, I had a bad OIS versions in there.

**Comment by Siegrift** [comment]
> and Airnode v0.10 was moving to OIS v0.10

This is not true. OIS has its own separate versioning. If there will not be any update to OIS schema (none is planned), the v0.10 Airnode will use ois@1.2.0.

> If not was is the purpose of OIS v0.1.2?

You can look at the [changelog](https://github.com/api3dao/ois/releases/tag/v1.2.0), but essentially we made OIS enforce only major.minor field for `oisFormat`.

**Comment by wkande** [comment]
I had a bad OIS version in my earlier comment. Sorry, but still not clear. What version of OIS does Airnode `v0.9` use?

**Comment by wkande** [comment]
Perhaps we can document here which version of OIS is needed for each Airnode version. The docs only use **major.minor** so the choices are `v1.1` and `v1.2`.

Airnode `v0.8` uses  OIS ___
Airnode `v0.9` uses  OIS ___
Airnode `v0.10` uses  OIS ___

**Comment by Siegrift** [comment]
Airnode v0.8 uses OIS v1.1
Airnode v0.9 uses OIS v1.2
Airnode v0.10 uses OIS v1.2

**Comment by wkande** [comment]
Doc version OIS `v1.2` created.

**Comment by wkande** [comment]
Not much to test here. I verified all the links and tested the search.

**Comment by dcroote** [comment]
@wkande - I think we still have to update `oisFormat` within config files for this to be closed

**Comment by wkande** [comment]
Looks like all config file examples have been changed.

**Comment by dcroote** [comment]
Ah sorry I should have been more clear- I meant updating config files within `airnode/v0.9` and `airnode/v0.10` to use `1.2.0` for `oisFormat`, will open a PR now.
