### ISSUE TITLE
Document Airnode request error codes

### ISSUE THREAD

**Issue by andreogle** [api3dao/old-api3-docs#108]
Requests coming to Airnode can be set to `status = "Errored"` for a number of different reasons. Each of these reasons has a specific "error code" integer that is returned to the calling contract as the `statusCode` argument here: https://github.com/api3dao/airnode/blob/6f31a4c27d40e86101673bf37d223fef6625dfdd/packages/protocol/contracts/AirnodeRrp.sol#L148 A status of `0` indicates success, while a status of `> 0` indicates that an error occurred and the integer can then be used to determine what exactly went wrong.

Currently, this list of error codes is documented here: https://github.com/api3dao/airnode/tree/master/packages/node#behaviour but this should rather be documented in the Airnode RRP documentation. The list of error codes and their descriptions should not be in a Google sheet.

**Comment by andreogle** [comment]
Ah I see there is actually a section here: https://docs.api3.org/pre-alpha/protocols/request-response/request.html#_1-fulfill about the error codes with a reference to the node README and Google sheet. I think it would be better for these error codes and descriptions to live with the rest of the documentation.

**Comment by wkande** [comment]
@andreogle : can you tell me where you are suggesting the error codes go exactly? Right now in `/pre-alpha` and `/next` they are in reference style docs. Maybe they should be a separate doc as well with more detail?

**Comment by wkande** [comment]
The **Request Outcomes** (there are 3) in the docs do not seem to relate well to the list of **Statuses** in the google sheet of [Airnode Error Scenarios](https://docs.google.com/spreadsheets/d/1DanVn7WyP96D5max2_5T5enJz7TcCsRceoqDfDfCcnA/edit?pli=1#gid=0)

[Docs > Request Outcomes](https://docs.api3.org/next/reference/protocols/request-response/request.html#request-outcomes)

Are the **Statuses** (there are 5) in the google sheet the same as **Request Outcomes** or a different concept when speaking to what a request can expect as outcomes.

At this point, I am just adding the spreadsheet contents into the doc. We can see if it looks and makes sense but I am not sure it does.

**Comment by andreogle** [comment]
The 5 **statuses** from the Google sheet are internal Airnode statuses that get assigned to each request. There are actually 6 statuses now - "Submitted" was added for requests that were pending/valid, have a response from the API and were submitted as a transaction back to the chain.

The important thing is the `statusCode` as this answers the question "why did the request fail". Both the requester and API provider might want to know this.

Both should also know about the "blocked" and "ignored" behaviour as this is unique. I would probably drop the table and just have a section explaining the process. Having the other statuses there will probably just end up confusing users. How about something like:

"""
Airnode is stateless, which means that there is no database storing which requests have been fulfilled or failed, which are waiting on confirmations and which are still pending. This information is retrieved from the chain on each request-response cycle (roughly every minute). During each cycle, retrieved requests needs to be ordered in the same way to ensure they are submitted using the same nonce. This is important because it's possible for a transaction to not have been confirmed by the time the next cycle runs. If this happens, the transaction is re-submitted with a "faster" transaction fee, overwriting the previous transaction.

However, Airnode is also dependent on the blockchain provider to supply it with the onchain data. If the blockchain provider is unavailable for whatever reason, it is possible that a request cannot be fully validated, which means that it cannot be submitted back to the blockchain. As mentioned above, keeping requests in the same order, using the same nonce is critical. Therefore, any request that cannot be fully validated due to a blockchain provider error becomes "blocked". This means that it and any requests after it are unable to be submitted during the current cycle and will be retried during the following cycle. It is important to note that this is specific to each requester. e.g. a request sent from requester A that becomes "blocked", will not block requests sent from requester B.

After X blocks (20 by default for EVM chains), any requests that would become "blocked", will instead become "ignored". This means that Airnode will stop attempting to process the request in order to process later requests.
"""

Feel free to edit as needed though. Not 100% sure everything I've written here makes sense

**Comment by wkande** [comment]
This helps thanks. When you say _drop the table_ I think you mean the **status table** but keep the **code table** in the docs?

**Comment by andreogle** [comment]
Yeah that's correct. We need to keep the codes table 👍🏻

**Comment by wkande** [comment]
There is more talk about reviewing status codes which may result in changes and thus changing docs.

See [api3dao/airnode - Issue 495 - Review and document status codes](https://github.com/api3dao/airnode/issues/495)

**Comment by bbenligiray** [comment]
I'm closing https://github.com/api3dao/airnode/issues/495, this will be tracked by https://api3dao.atlassian.net/jira/software/projects/AN/boards/18/backlog?selectedIssue=AN-71

**Comment by wkande** [comment]
Error code are no longer a factor. The docs have been updated to discuss how the following work:

- fulFill
- fail
- blocked
- ignore

`fulFill` is the only outcome from Airnode that a requester can expect to be called. `fail` will stop in AirnodeRrp where it will update the contract storage.
