### ISSUE TITLE
dAPI browser doesn't support Beacon sets and will soon break

### ISSUE THREAD

**Issue by bbenligiray** [api3dao/old-api3-docs#1095]
We have a [dAPI browser](https://docs.api3.org/dapis/reference/dapi-browser.html), which IIRC was a temporary solution while we were working on the [Market](https://market.api3.org/dapis). It has two main issues:
- Unlike the Market, it doesn't support Beacon sets. Visualizing Beacon sets in a good looking way is not a trivial problem.
- It depends on an API that serves the data from the [operations repo](https://github.com/api3dao/operations). We stopped using the operations repo and its replacement doesn't have an equivalent API that is readily available.

Another point to consider is that we will be switching to v1 docs soon, which doesn't necessarily include this dAPI browser. The easiest solution here feels like taking down the dAPI browser and rely on the Market for all visualization needs.

**Comment by wkande** [comment]
@bbenligiray - I have seen this coming and spoken to @aquarat a little. I can remove the dAPI Browser. Its main purpose was to expose the template behind a dAPI and as well as the Beacons behind it. I'm sure it can be re-written using the newer DB API operations Aaron is writing. But if we feel it is not needed it can be removed . `v1` of the docs now mentions the API3 Market, tonight's build will have it under **Explore > dAPIs**.

**Comment by bbenligiray** [comment]
I think removing for now is the easier solution
