### ISSUE TITLE
API key should be filled

### ISSUE THREAD

**Issue by drgy** [api3dao/old-api3-docs#11]
If I understood correctly API key in `config.json` has to be filled out or provided in `.env` file. This makes description [here](https://github.com/api3dao/api3-docs/blob/8e41ab2597cb19cb75e4904d6e9b214287c1d738/airnode/security-json.md#the-user-flow) deprecated, as the [related issue](https://github.com/api3dao/airnode/issues/163) was closed.

**Comment by bbenligiray** [comment]
Fixed in https://github.com/api3dao/api3-docs/pull/12 and https://github.com/api3dao/api3-docs/pull/13
