### ISSUE TITLE
Describe where to find logs for Airnode deployed to a cloud provider 

### ISSUE THREAD

**Issue by dcroote** [api3dao/old-api3-docs#1106]
e.g. CloudWatch in AWS. It would also be helpful to describe the organization of log groups (e.g. for gateway vs. blockchain requests).

Perhaps this would work well as a new page, e.g. "Monitoring Airnode", within the API Providers section following the "Deploying Airnode" page.

**Comment by wkande** [comment]
Good idea, good location.

**Comment by dcroote** [comment]
@martinkolenic  - testing this should be simple: the next time you are deploying to GCP and AWS just confirm that the instructions to view the logs are understandable.
