### ISSUE TITLE
Allow API call to be skipped in endpoints

### ISSUE THREAD

**Issue by amarthadan** [api3dao/old-api3-docs#1118]
Documentation for https://github.com/api3dao/airnode/issues/1527
One of the TODOs from the Migration guide should be part of this issue (https://github.com/api3dao/api3-docs/pull/1174#issuecomment-1406386840)

**Comment by wkande** [comment]
I think we still need a short explanation (maybe a brief use case) as to why one would want to skip the API call.

**Comment by wkande** [comment]
@aTeoke , @metobom - I am working on this one today. Adding myself as an assignee.

**Comment by wkande** [comment]
@metobom and @aTeoke 
Please check this review at these preview links or in the code.

- [5.2. operation](https://api3-docs--pr1179-20230131-1118-ois-sk-a5t5tufj.web.app/ois/v1.4/ois.html#_5-2-operation)
- [Skip the API provider call](https://api3-docs--pr1179-20230131-1118-ois-sk-a5t5tufj.web.app/ois/v1.4/processing.html#skip-the-api-provider-call)

**Comment by metobom** [comment]
> @metobom and @aTeoke Please check this review at these preview links or in the code.
> 
> * [5.2. operation](https://api3-docs--pr1179-20230131-1118-ois-sk-a5t5tufj.web.app/ois/v1.4/ois.html#_5-2-operation)
> * [Skip the API provider call](https://api3-docs--pr1179-20230131-1118-ois-sk-a5t5tufj.web.app/ois/v1.4/processing.html#skip-the-api-provider-call)

* Is `API provider call` the right term? Should it be just `API call`? 
* I did not think of it but, in the random number generation example output will always be zero since `Math.random()` returns between 0 and 1 and `_type` in `reservedParameters` is `uint256`. If that's a problem, it can be changed to `Math.floor(Math.random() * 100)` to make it return between 0 and 100.

**Comment by aTeoke** [comment]
Let's change the example please.

**Comment by wkande** [comment]
> Is API provider call the right term? Should it be just API call?

I am fine either way:

- (Required: when calling an API provider operation)      **> becomes >**     (Required: when calling an API)
- Instead of calling an API provider operation     **> becomes >**    Instead of calling an API

**Comment by wkande** [comment]
@amarthadan - I updated the Airnode `v0.10` migrations guide with regards to skipping an API call. It will show up in the next push to this PR.

**Comment by wkande** [comment]
@metobom @aTeoke @amarthadan - The PR has been updated with all requested changes. Please let me know if I can merge.

**Comment by aTeoke** [comment]
All good from my side
