### ISSUE TITLE
Default to DEBUG log level in quick deploy tutorials 

### ISSUE THREAD

**Issue by dcroote** [api3dao/old-api3-docs#1123]
Based on [this comment](https://github.com/api3dao/airnode/issues/1351#issuecomment-1326066076) and the subsequent discussion. The corresponding airnode issue is https://github.com/api3dao/airnode/issues/1552

**Comment by wkande** [comment]
@dcroote I was going to pull this one out of the backlog and add it to `v0.10` and `v0.11`. I assume that this is a matter of changing the `config.json` files followed by updating the  zip files?

```
"logLevel": "DEBUG",
```

**Comment by dcroote** [comment]
Correct!
