### ISSUE TITLE
Add a new reserved parameter to allow minConfirmations to be specified

### ISSUE THREAD

**Issue by amarthadan** [api3dao/old-api3-docs#1130]
Documentation for https://github.com/api3dao/airnode/issues/1393
One of the TODOs from the Migration guide should be part of this issue (https://github.com/api3dao/api3-docs/pull/1174#issuecomment-1406386840)

**Comment by wkande** [comment]
I updated the migration guide TODO for **_Skip the API call_**  in PR#1118
