### ISSUE TITLE
Setup OIS v1.4 for release with Airnode v0.10

### ISSUE THREAD

**Issue by dcroote** [api3dao/old-api3-docs#1150]
`_minConfirmations` and `_gasPrice` reserved parameters were added to OIS and will be released as v1.4.0 for use in Airnode v0.10

**Comment by wkande** [comment]
@dcroote - We currently have Airnode `v0.10` set to use OIS `1.3`. So this has changed? If we move Airnode `v0.10` to use OIS `v1.4` then. `v1.3` becomes orphaned in that it is not related to any Airnode version.

**Comment by wkande** [comment]
So we will create `v1.4` and leave `v1.3` as it is.
