### ISSUE TITLE
Create v0.11 Migration Guide branch

### ISSUE THREAD

**Issue by dcroote** [api3dao/old-api3-docs#1184]
TODO after v0.11 doc set is created.

The purpose is to create a migration guide branch that is added to during v0.11 development instead of going back through all issues and commits right before the release to try and figure out what changes could impact the user.

**Comment by wkande** [comment]
Good idea.

**Comment by wkande** [comment]
@dcroote  -  I just assumed you are doing this but let me know otherwise. I hopefully will have the `v0.11` release of the docs ready Feb 7th.

**Comment by dcroote** [comment]
Yes I'll do it. Also you tagged someone that isn't me in your last comment 😅

**Comment by wkande** [comment]
@dcroote I just created the Airnode `v0.11` doc set. In doing so I also made an adjustment to the `migration.md` doc, slight change to the how the `<HEADINGs/>` are presented.

**Comment by dcroote** [comment]
Closing as the draft / WIP PR branch is available here: https://github.com/api3dao/api3-docs/pull/1193
