### ISSUE TITLE
quick-deploy-container tutorial is broken: "stage" invalid

### ISSUE THREAD

**Issue by dcroote** [api3dao/old-api3-docs#1195]
The tutorial is currently broken in v0.9, v0.10, and v0.11 because the value for `stage` under `nodeSettings` is invalid. The character limit (checked [here](https://github.com/api3dao/airnode/blob/5b2c06075f1082d00a057512cc57396087be1421/packages/airnode-validator/src/config/config.ts#L299) in `airnode-validator`) is 16, whereas the stage value provided in config.json, `tutorial-container`, is 18 characters. The `config.json` files need to be fixed and the zip files re-uploaded.

```
Error: Invalid Airnode configuration file: [
  {
    "validation": "regex",
    "code": "invalid_string",
    "message": "Invalid",
    "path": [
      "nodeSettings",
      "stage"
    ]
  }
]
```

**Comment by wkande** [comment]
- Moved Mac/WSL2/PowerShell tab to first position.
- Moved Linux to last position.
- Updated the deploy paragraph for port and host networking.

**Comment by wkande** [comment]
Nothing here to test really. I would just push this along to **Done**. It has already been deployed.
