### ISSUE TITLE
Create OIS `v2.0` doc set

### ISSUE THREAD

**Issue by wkande** [api3dao/old-api3-docs#1201]
This will need migration to VitePress as well.

**Comment by wkande** [comment]
Not much to test here. Maybe see if OIS v`2.0` is live, click a few links and check fro error in your browser console.

**Comment by dcroote** [comment]
Will links between Airnode v0.11 and OIS v2.0 be updated later? There is also a need to update instances of `oisFormat` in OIS v2.0 and Airnode v0.11 from `1.4.0` to `2.0.0`. Also the [Releases](https://docs.api3.org/ois/v2.0/#releases) table.

**Comment by wkande** [comment]
@dcroote - Usually the links do get updated later because I need the tags to exist in the repos. But since the  OIS `v2.0` tag already exists that one can be done now inside the Airnode `v0.11` doc set, so I will get on it today. 

I will also update the `oisFormat` in both `v0.11` `v2.0` today.

**Comment by wkande** [comment]
I also think you meant internal links between OIS and Airnode docs sets. I see a few of those to fix as well, today.

**Comment by aTeoke** [comment]
Also for the environment - we will use Node 18 for Airnode 0.11.0. And is the VitePress link already available or that will be done later?

**Comment by wkande** [comment]
@dcroote - The links are fixed.
@aTeoke   - am looking at the node version now, will create a new issue for this..
