### ISSUE TITLE
Verify Airnode `v0.11` uses node `v18`

### ISSUE THREAD

**Issue by wkande** [api3dao/old-api3-docs#1206]

**Comment by wkande** [comment]
@aTeoke This is to look into your request.

**Comment by dcroote** [comment]
Yes: https://github.com/api3dao/airnode/pull/1647

**Comment by dcroote** [comment]
Or wait- do you mean `environment` in processing specifications of `config.json`?

**Comment by wkande** [comment]
@dcroote @aTeoke - So Airnode uses node 18, but I thought that the `environment` field  for pre/post processing was user defined. So why can't it be whatever node version they want?

**Comment by dcroote** [comment]
`environment` is restricted to two values here: https://github.com/api3dao/ois/blob/59b3dc3f53e45a8e700b340d3af0c0db64a9fade/src/ois.ts#L273

**Comment by dcroote** [comment]
Closing after our discussion related to https://github.com/api3dao/api3-docs/pull/1207
