### ISSUE TITLE
remove `airnodeAddressShort`

### ISSUE THREAD

**Issue by wkande** [api3dao/old-api3-docs#1208]

**Comment by wkande** [comment]
`airnodeAddressShort` is used in the manual removal instructions It should use `deploymentId`. Also be sure it has been moved in any examples of `receipt.json`

**Comment by wkande** [comment]
@amarthadan Right now I am looking to make this correction for versions `v0.10` and `v0.11`. Are there other versions that need changing?

**Comment by amarthadan** [comment]
No, this was introduced in `v0.10`.
