### ISSUE TITLE
Blog posts navbar item

### ISSUE THREAD

**Issue by bbenligiray** [api3dao/old-api3-docs#121]
Copy-pasting from YEET on Discord:

> https://docs.api3.org/pre-alpha/#learn-more-about-api3 I'd suggest this to have it's own page and not buried in "What is API3" page. More specifically "Blog Posts" tab should be easy to reach.
> All the other sections like API3 website, The whitepaper, communities, github are mentioned either in top navigation bar or other pages. Except "Blog Posts" section.

I agree, it's a good idea to have blog posts as a navigation bar item. Also, they should be very up-to-date.

**Comment by wkande** [comment]
We have the medium posts as a line item in the sidebar for **/next.**  https://docs.api3.org/next/medium-posts.html. So the following image is what I am thinking.

![Screen Shot 2021-07-04 at 9 33 11 AM](https://user-images.githubusercontent.com/3522283/124390912-079a4080-dcab-11eb-8f26-52e53c271202.png)


Or are you talking about the navbar which is the black bar across the top of the page? Adding more items to the navbar becomes problematic in that the responsive properties of the page get distorted as the user shrinks the width of the page.

I will double check but the articles should be up-to-date except for on Sasa did and is on my list to add today.

**Comment by wkande** [comment]
The Blog Posts page has been added to the sidebar. Also, the blog component has been updated to show posts by group or by date.
