### ISSUE TITLE
Weird members/overview URL

### ISSUE THREAD

**Issue by bbenligiray** [api3dao/old-api3-docs#122]
Copy-pasting from YEET on Discord:

> https://docs.api3.org/pre-alpha/members/#frontmatter-title should be https://docs.api3.org/pre-alpha/members/#overview for the sake of url consistency. Changing the h1 tag id would do I think.

**Comment by wkande** [comment]
The correct behavior would be to use https://docs.api3.org/pre-alpha/members/ and rename **the overview.md** page to **README.md**. Vuepress works best when the default page for a directory (or sidebar groups) is a README. I have changed the sidebar JSON and renamed overview.md to README.md.
