### ISSUE TITLE
QRNG airnode response time in Fantom network

### ISSUE THREAD

**Issue by EthanBlockson** [api3dao/old-api3-docs#1232]
Using Quintessence Random Numbers provider:

`airnode` 0x224e030f03Cd3440D88BD78C9BF5Ed36458A1A25
`xpub` xpub6CyZcaXvbnbqGfqqZWvWNUbGvdd5PAJRrBeAhy9rz1bbnFmpVLg2wPj1h6TyndFrWLUG3kHWBYpwacgCTGWAHFTbUrXEg6LdLxoEBny2YDz
`endpointIdUint256` 0xffd1bbe880e7b2c662f6c8511b15ff22d12a4a35d5c8c17202893a5f10e25284

In Fantom (Mainnet) with `AirnodeRrpV0` address 0xa0AD79D995DdeeB18a14eAef56A549A04e3Aa1Bd it takes nearly 110 blocks to get a Fulfill response. (132 seconds or 2.2 minutes).

But documentation states that `minConfirmations` is 1. Is that problem with node or it's standard response time?

2 minutes is way too long for comfort user experience...

_We also discussed this in API3 Forum._ Can you please add the risky option to get Fulfill after a 1-3 blocks? Because from my point of view, even if reorg occurs, it will just cancel the transactions, but a lot of time will be saved in total.

**Comment by Ashar2shahid** [comment]
As discussed in [the](https://forum.api3.org/t/qrng-minconfirmations/1872/2) forum post Quintessence has a minConfirmation of 80 blocks on fantom. We will be rolling out an endpoint with 1 minConfirmation soon, expected timeline is 1-2 weeks after v0.11 launches which should suffice for your needs
