### ISSUE TITLE
Remove the id field from config.json

### ISSUE THREAD

**Issue by bbenligiray** [api3dao/old-api3-docs#124]
See https://github.com/api3dao/airnode/issues/411

After we remove the `id` field from `config.json`, we need to also remove it from the `/next` docs

**Comment by bbenligiray** [comment]
This is done recently
https://github.com/api3dao/airnode/pull/414

**Comment by wkande** [comment]
So what is the unique identifier now, `ois.title`? If so can it be changed later. I saw a posting @bbenligiray made taking about it.

Is this in any way related to issue [issue #60](https://github.com/api3dao/api3-docs/issues/60)?

**Comment by wkande** [comment]
The id has been removed from several docs. It appears to still be in the receipts.json file example that goes with the airnode-starter. A new issue has been created for this as the airnode-starter repo is in need of an update given the ongoing Airnode changes for 0.1.0. See #136
