### ISSUE TITLE
It's not clear what the `in` field for POST operation parameters should be

### ISSUE THREAD

**Issue by bbenligiray** [api3dao/old-api3-docs#129]
Received this Discord question (to which the answer is yes)
> How to configure config.json for post request? Should I include body as query parameter?

OpenAPI tooling that I had been using had the body parameters of POST operations defined as `in: query` (and it works just fine for `application/json` content type that is not nested, which is all we do anyway). After looking it up,I found out that body parameters are in fact defined in a [`requestBody`](https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.0.3.md#requestBodyObject) object, so the way we go is actually quite non-standard. This needs to be documented, i.e., it should say "If you are integrating a POST operation, define the body parameters with `in: query`. Note that only non-nested `application/json` content-type is supported." We should also probably consider updating OIS to conform to OpenAPI better here.

**Comment by wkande** [comment]
The following (OLD) statement is in:

- /pre-alpha > ois.md 
- /pre-alpha > api-integrations.md
- /next > ois.md
- /next > api-integrations.md

**OLD:**
For POST methods use type `query` for requestBody parameters. Airnode will convert all `query` types to `requestBody` when calling the API operation if the method is POST. 

It has been updated with (NEW):

**NEW:**
When integrating a POST method, define the body parameters with `in: query`. Airnode will convert all `query` types into the `requestBody`. Note that only the non-nested application/json content-type is supported.
