### ISSUE TITLE
Enclose %cd% by quotations in Docker commands for Windows

### ISSUE THREAD

**Issue by bbenligiray** [api3dao/old-api3-docs#141]
Windows users replace `$(pwd)` with `%cd%` while using the Docker commands. However, if the path returned by `%cd%` contains any whitespace, Docker throws `Invalid Reference Format`. We should use `"%cd%"` instead.

See this issue for more information:
https://github.com/api3dao/airnode/issues/457

**Comment by wkande** [comment]
All docs that display a docker command now display the command in a tab set.

@bbenligiray @

![Screen Shot 2021-08-04 at 5 06 14 PM](https://user-images.githubusercontent.com/3522283/128266623-1f339734-75b5-419c-ab55-6a4ea0d2874b.png)

![Screen Shot 2021-08-04 at 5 07 11 PM](https://user-images.githubusercontent.com/3522283/128266700-33180997-72a7-4f86-89ed-f6833e4d30fb.png)
