### ISSUE TITLE
Possible videos

### ISSUE THREAD

**Issue by wkande** [api3dao/old-api3-docs#147]
Back in the spring timeframe @bbenligiray had asked about creating (3) videos. This issue serves to hold onto the idea until we can decide to move forward. The original issues (#48 #49 #50) have been closed and consolidated here.

- Create walkthrough videos for running the node in the cloud documentation
- Create walkthrough videos for running the node locally documentation
- Create walkthrough videos for airnode-starter documentation

**Comment by bbenligiray** [comment]
There is https://drive.google.com/file/d/1pvmD0FCPVvzzwa2YNkGsVKXEEO2UB1hx/view from @jgcogsystematictrading
