### ISSUE TITLE
Document that if method is POST, query parameters go into body

### ISSUE THREAD

**Issue by bbenligiray** [api3dao/old-api3-docs#156]
In OAS, specifying a request body is pretty [cumbersome](https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.1.0.md#request-body-object) because it needs to be flexible.

In OIS, we only support a non-nested JSON as a body, so body parameters are specified similarly to query parameters. As a result, [here](https://docs.api3.org/pre-alpha/airnode/specifications/ois.html#_4-4-1-2-in), if the method is POST and the `in` value is `query`, the parameter goes into the body. This needs to be specified because some users are confused about how they should be specifying body parameters for POST requests and there is nothing in the docs about that.

**Comment by wkande** [comment]
We have had this discussion before when I changed the docs for OIS on **/next**. See [/next API Ingtegrations](http://localhost:8080/next/grp-providers/guides/provider/api-integration.html).

So I will get this into pre-alpha as well. I think a small mention in the specification files might be warranted as well.

**Comment by bbenligiray** [comment]
Thanks, I only checked pre-alpha and saw that it isn'tt there

**Comment by wkande** [comment]
Updated text with regards to POST method parameters. @bbenligiray 

### API Integration

After specifying the path and method of an API operation, the final step is to specify its parameters. Each parameter is an object in the `apiSpecifications.paths.{PATH}.{METHOD}.parameters` array, with the fields `in` and `name`. `in` tells where the parameter goes in the HTTP request and `name` tells the name that the parameter value will be sent under. Currently Airnode supports the following parameter types for use with `in`. 

- query
- header
- path
- cookie

For POST methods use the type `query` for requestBody parameters. Airnode will convert all `query` types to `requestBody` when calling the API operation if the method is POST.

---
### Specification Files

For POST methods use the type `query` for requestBody parameters. Airnode will convert all `query` types to `requestBody` when calling the API operation if the method is POST.

---
See using these production links.

**/pre-alpha**
[ois](https://docs.api3.org/pre-alpha/airnode/specifications/ois.html#_4-4-1-2-in)
[api-integration](https://docs.api3.org/pre-alpha/guides/provider/api-integration.html#operation-parameters)

**/next**
[ois](https://docs.api3.org/next/reference/specifications/ois.html#_4-4-1-2-in)
[api-integration](https://docs.api3.org/next/grp-providers/guides/provider/api-integration.html#parameters-operation)
