### ISSUE TITLE
Clarify how the ENS names work for DAO proposals

### ISSUE THREAD

**Issue by bbenligiray** [api3dao/old-api3-docs#160]
We now support ENS names (instead of addresses) while making proposals

https://forum.api3.org/t/dao-dashboard-update-august-16-2021/497

There is a potential pitfall here:
- Someone buys an ENS name, makes a proposal with it
- While the proposal is active, they point their ENS name to another address
- The proposal passes. They expect to receive the funds to the new address, but they will receive them at the old address

So what happens is that while making the proposal, the dashboard looks up what address the ENS name is pointing to, and hardcodes that in the proposal on-chain. After that point, the contracts don't care about what you do with your ENS name.

**Comment by wkande** [comment]
@bbenligiray 

The site https://staging.api3.eth.link/#/ seems to be down and I do not qualify to create a proposal on PROD. I wanted to verify the _ENS name_ goes into the field **TARGET CONTRACT ADDRESS** which I'm sure it does?



![Screen Shot 2021-08-19 at 11 18 09 AM](https://user-images.githubusercontent.com/3522283/130114441-7d17fc8b-434f-4bed-af61-aca2864bd4d2.png)

**Comment by wkande** [comment]
## Using ENS Names

If you use an ENS name when creating a proposal, the Dashboard contracts will remember the public address assigned to the ENS name at the time of the proposal. If the proposal passes, the payout will go to the public address the ENS name pointed to when the proposal was created.

Therefore changing the address of the ENS after making a proposal can be problematic. Consider the following. 
- You buy an ENS name and assign it to a public address you own. 
- You make a proposal that uses the ENS.
- While the proposal is active, you point your ENS name to another address.
- The proposal passes. You expect to receive the funds at the new address, but you will receive the funds at the old address.

**Comment by bbenligiray** [comment]
As a note, the wording is iffy on this and I don't have time to fix it

**Comment by wkande** [comment]
Less iffy?

## Using ENS Names

When you create a proposal using an ENS name, the public address of the ENS is recorded on-chain and will be used for any payout should the proposal pass. Therefore changing the address of the ENS after the creation of a proposal will not result in the updated address being used.

Going off the summary phrase above, I plan to inject it into the **Create a Proposal** instructions under the step for adding parameters of the target contract signature in **/next**. For **/pre-alpha** it will be in the proposal docs. Once deployed I will update this issue with links to the usage in the docs.

**Comment by wkande** [comment]
@bbenligiray 

I integrated the ENS statement into **/next** [Working with Proposal > Create Proposal](https://docs.api3.org/next/grp-members/dashboard/proposals.html#proposal-creation) specifically in (8) _Parameters_ field. It makes sense by speaking to both the use of a public address or ENS name there. Also added is the idea of using IPFS in the (4) _Description_ field.

In **/pre-alpha** there is just a blurb about ENS names in [Proposals](https://docs.api3.org/pre-alpha/members/governance/proposals.html). It might be best to move the entire doc from /next to /pre-alpha as the Proposals doc in /pre-alpha is of little value, perhaps it can be trimmed down to just proposals types.

**Comment by bbenligiray** [comment]
I think it's already running too long, I would just add this after the Proposal Creation section instead.

## Using ENS names instead of addresses

You can use the [ENS app](https://app.ens.domains/) to register a name and associate it with an Ethereum account. Then, while entering your proposal parameters, you can use this ENS name instead of the account address. Before making the transaction that will create the proposal, the DAO dashboard will look up the address that the ENS name is pointing to, and use the raw address in the proposal. Therefore, changing the address that the ENS name is pointing to after this look up operation **WILL NOT** have an affect on the proposal.

If you also want the voters to see the ENS name instead of the raw address to make your proposal more readable, you will have to use the [ENS app](https://app.ens.domains/) to set a reverse record pointing to your ENS name (i.e., you need to have your raw address point to the ENS name). For example, if you are making a proposal to make a `transfer(address,amount)` call to an ERC20 token contract where `address` will be the address of a multisig wallet, you can [set a reverse record with the multisig](https://medium.com/the-ethereum-name-service/you-can-now-manage-ens-names-with-gnosis-safe-9ddcb7e6c4ac) to your ENS name for it to appear on the proposal details page. See Parameters in [this proposal](https://api3.eth.link/#/history/secondary-6) for an example.

**Comment by wkande** [comment]
Added the new ENS names section. Looks good. Cleaned out the (4) parameters area making things less cluttered. Deployed.
