### ISSUE TITLE
Sidebar doesn't autoscroll to the selected item

### ISSUE THREAD

**Issue by bbenligiray** [api3dao/old-api3-docs#17]
When the user follows a link (for example click https://api3dao.github.io/api3-docs/next/grp-providers/protocols/request-response/designated-wallet.html from an external page) the sidebar should automatically scroll to make the current page visible.

**Comment by bbenligiray** [comment]
I guess this is not an issue if the sidebar doesn't grow too long

**Comment by wkande** [comment]
Just wanted to note that I looked into this. Autoscroll behavior is not part of the VuePress sidebar in v1. I checked VuePress v2 now in beta 4 and the behavior is the same.

The sidebar does highlight the new file but leaves the sidebar position as the user left it. No sure why they have chosen this behavior.
