### ISSUE TITLE
Add http-server to devDependencies in package.json?

### ISSUE THREAD

**Issue by dcroote** [api3dao/old-api3-docs#215]
While not strictly necessary to run `yarn docs:dev` locally, building the docs to run [link validation](https://docs.api3.org/dev/link-validator.html#step-2-start-http-server) requires it.

**Comment by wkande** [comment]
I think that a change may be needed to the /dev instructions. Since I have http-server installed globally the dev dependency is not needed. But I can see that some may wish to run it as a dev dependency. I will do a quick update to /dev for this as an explanation.

**Comment by dcroote** [comment]
Makes sense to me!
