### ISSUE TITLE
Switching between "Airnode" and "Dao members" returns me to "pre-alpha"

### ISSUE THREAD

**Issue by Siegrift** [api3dao/old-api3-docs#279]
This seems confusing to me, I would expect to stay on the same version (I started of from next).
Or bettter said, I'd not expect the version to be changed when clicking those buttons as they just seem like "tabs"

![image](https://user-images.githubusercontent.com/22679154/136426880-9b279947-786a-4906-a6b8-007161819a0a.png)

**Comment by wkande** [comment]
That one has been on my mind. Right now it defaults to the latest version. My plan is to fix that when I add the new API3 icon. I am waiting on Leandro to deliver the icons first. I'm guessing late next week.

**Comment by wkande** [comment]
@Siegrift  -  This behavior has been changed, Airnode now remembers which version it was on last when going between Airnode, Dao Members and API3. However it should be noted that when a user returns to the landing page from API3 or DAO Members, Airnode will revert to the latest version.
