### ISSUE TITLE
Remove /next from version pick-list

### ISSUE THREAD

**Issue by wkande** [api3dao/old-api3-docs#41]
It may make sense to remove the **/next** version from the version's pick-list.

Currently, **/next** is not included in the pick-list on production. It is however within the pick-list for local development. This does not mirror production while in development.

Below is how the pick-list looks in development.

![version-picklist](https://user-images.githubusercontent.com/3522283/113129117-c5f38880-91d7-11eb-90be-a1b4481aec16.png)

**New version rules:**

- All subfolders in /docs are base routes
- A base route becomes a version of the docs when declared a version in config.json
    ```json
    versions:[
      {"name":"0.1.0", "url":"/0.1.0/"},
      {"name":"pre-alpha","url":"/pre-alpha"}
    ],
    ```
Under these new rules /next is still accessible in production and development by using the browser's URL bar.

**Comment by bbenligiray** [comment]
I agree, I see no downside of not having **next** on the list.

**Comment by wkande** [comment]
Completed. **/dev** versions.md updated to reflect the new versioning scheme.
