### ISSUE TITLE
Incorrect derivation path

### ISSUE THREAD

**Issue by bbenligiray** [api3dao/old-api3-docs#480]
Here https://docs.api3.org/airnode/v0.3/concepts/sponsor.html#derivation-path the derivation path is
```
m / 0 / sponsor && 0x7FFFFFFF / (sponsor >> 31) && 0x7FFFFFFF / (sponsor >> 62) && 0x7FFFFFFF / (sponsor >> 93) && 0x7FFFFFFF / (sponsor >> 124) && 0x7FFFFFFF / (sponsor >> 155) && 0x7FFFFFFF
```
This belongs to pre-alpha and changed in v0.2+. It should be
```
m/44'/60'/0'/0/...
  /1st least significant 31-bits of the sponsor address (sponsor && 0x7FFFFFFF)…
  /2nd least significant 31-bits of the sponsor address (sponsor >> 31 && 0x7FFFFFFF)…
  /3rd least significant 31-bits of the sponsor address (sponsor >> 62 && 0x7FFFFFFF)…
  /4th least significant 31-bits of the sponsor address (sponsor >> 93 && 0x7FFFFFFF)…
  /5th least significant 31-bits of the sponsor address (sponsor >> 124 && 0x7FFFFFFF)…
  /6th least significant 31-bits of the sponsor address (sponsor >> 155 && 0x7FFFFFFF)
```
This needs to fixed for all v0.2+ versions

**Comment by wkande** [comment]
Thanks I will update all versions requeired.

**Comment by bbenligiray** [comment]
As a note, this will be changed again in v0.4 according to https://api3dao.atlassian.net/browse/AN-453 (so the base path will be `m/44'/60'/0'/1/`) but you can ignore that for now and we can do the docs update while handling that issue.

**Comment by wkande** [comment]
@bbenligiray v0.2+ has been updated. A TODO comment has been placed into the docs for v0.4 to make an update for AN-453 when it hits the Documentation column on the JIRA board. See [PR 429](https://github.com/api3dao/api3-docs/pull/492):
