### ISSUE TITLE
nodeVersion on Configuring Airnode looks wrong

### ISSUE THREAD

**Issue by An-dz** [api3dao/old-api3-docs#498]
In the [nodeVersion](https://docs.api3.org/airnode/v0.3/grp-providers/guides/build-an-airnode/configuring-airnode.html#nodeversion) section of Configuring Airnode it claims the current node version is `1.0.0`, but all the quick deploy examples shows `0.3.1` which looks more correct to be honest.

**Comment by dcroote** [comment]
Nice catch @An-dz. This also affects the equivalent [v0.2](https://docs.api3.org/airnode/v0.2/grp-providers/guides/build-an-airnode/configuring-airnode.html#nodeversion) and [upcoming v0.4](https://docs.api3.org/airnode/v0.4/grp-providers/guides/build-an-airnode/configuring-airnode.html#nodeversion) pages, but [not pre-alpha](https://docs.api3.org/airnode/pre-alpha/guides/provider/configuring-airnode.html#nodesettings). See #502 for a fix that avoids having this value be updated every version (including patch).
