### ISSUE TITLE
Bug on example requester code

### ISSUE THREAD

**Issue by An-dz** [api3dao/old-api3-docs#499]
In _Calling an Airnode_, under [Step \#2: Implement the request logic](https://docs.api3.org/airnode/v0.3/grp-developers/call-an-airnode.html#step-2-implement-the-request-logic) there's a minor bug in the example code coming from the pre-alpha code. On line 21 it should be `airnodeRrp`:

```diff
-      bytes32 requestId = airnode.makeFullRequest( // Make the Airnode request
+      bytes32 requestId = airnodeRrp.makeFullRequest( // Make the Airnode request
```

**Comment by wkande** [comment]
Thanks for the catches in this issue and issue 498. I hope to get at them both in the next few days.

**Comment by wkande** [comment]
This will be deployed later with today's scheduled build.
