### ISSUE TITLE
Handle URLs that contain an anchor and use the /latest redirect for the airnode version

### ISSUE THREAD

**Issue by dcroote** [api3dao/old-api3-docs#540]
When using the direct link to the `v0.3` page, the following anchor works:
https://docs.api3.org/airnode/v0.3/grp-providers/guides/build-an-airnode/configuring-airnode.html#creating-secrets-env

but when replacing `v0.3` with `latest`, the user is not brought to the anchor within the page:
https://docs.api3.org/airnode/latest/grp-providers/guides/build-an-airnode/configuring-airnode.html#creating-secrets-env

**Comment by aquarat** [comment]
I've just encountered the same issue.

**Comment by dcroote** [comment]
The 404 page flashes briefly for me, but the redirect works and retains the anchor so I'll close.
