### ISSUE TITLE
SearchBox results displays multiple versions of Airnode

### ISSUE THREAD

**Issue by wkande** [api3dao/old-api3-docs#573]
**MacBook**: On a preview site the search box shows results across multiple versions of Airnode but not on production or localhost.

**Linux**: localhost does have the issue, production is OK.

**Windows**: @dcroote, can you try this on your windows box?

![Screen Shot 2022-01-30 at 5 59 32 AM](https://user-images.githubusercontent.com/3522283/151700741-b1b0b944-cf33-40c4-94cc-1e5df15c1c2b.png)

**Comment by dcroote** [comment]
Windows:
- Production: single version

WSL2:
- `yarn docs:dev` - multiple versions
- `yarn docs:build` followed by `http-server` - multiple versions
