### ISSUE TITLE
Link Validator 403/timeouts external links

### ISSUE THREAD

**Issue by wkande** [api3dao/old-api3-docs#578]
Some external sites do not respond in a timely manner. Add a retry for all (external only) links that do not respond properly.

**Comment by wkande** [comment]
@kolenic-martin 
This is an update to the script that checks links using an actual VuePress build, as opposed to the link-check plugin which reads the markdown files. To test it you can [**follow these instructions**](https://docs.api3.org/dev/link-validator.html) for the script called `link-validator.js`.

This will test all links in all doc sets, over 9,000 of them I think.
```sh
node ./libs/link-validator.js  http://127.0.0.1:8082  ./docs/.vuepress/dist/
```

This will test only Airnode `v0.8`.

```sh
node ./libs/link-validator.js  http://127.0.0.1:8082  ./docs/.vuepress/dist/airnode/v0.8/
```

**Comment by martinkolenic** [comment]
Hi, @wkande, I tested the new script and this works just fine. Takes a while, though, but that's probably expected given the sheer volume of the links to check. I've tested both variants, the v0.8 ran quicker, just as expected. I'm moving this to Done.
