### ISSUE TITLE
Proofread Airnode > Developers > Overview doc

### ISSUE THREAD

**Issue by martinkolenic** [api3dao/old-api3-docs#592]
I'm working through the document and proofreading it. I'll work on this in a separate branch

**Comment by wkande** [comment]
@kolenic-martin Please note that I will create `v0.5` of the docs tomorrow. So any changes you have to the `v0.4` docs will not appear in `v0.5` as I make a copy of `v0.4` to roll over. Best to get your PR in soon or the corrections you make to `v0.4` will not be in `v0.5`. Thus they would need to be corrected again.
