### ISSUE TITLE
Document allowed OIS titles

### ISSUE THREAD

**Issue by bbenligiray** [api3dao/old-api3-docs#60]
Some restrictions will be applied to OIS titles
https://github.com/api3dao/airnode/issues/293
These need to be added to the docs, similar to
https://github.com/api3dao/api3-docs/blame/1ee970633eff63d6d0250cae9703c3d2d971970a/docs/next/technology/deployment-files/config-json.md#L233

**Comment by wkande** [comment]
Added both to /pre-alpha and /next. 

This issue is related somewhat to api3dao/airnode#293.
----

# 2. `title`

(Required) The OIS title. Title field is at most 64 characters, can only include alphanumeric characters, hyphens, underscores and whitespaces.

OAS equivalent: `info.title`
