### ISSUE TITLE
Insurance for Beacons

### ISSUE THREAD

**Issue by bbenligiray** [api3dao/old-api3-docs#603]
[This](https://docs.api3.org/beacon/v0.1/introduction/why-use-beacons.html) understandably says only the dAPIs will be insured, because Beacon insurance wasn't mentioned in the whitepaper. However, that was more before Beacons as a concept didn't exist back then. It's likely that we'll also want to insure Beacons, so this page will need to be updated as more information about that is made public.

**Comment by wkande** [comment]
I think in the newer dAPI doc set we have this covered.
