### ISSUE TITLE
Beacon IDs page is confusing

### ISSUE THREAD

**Issue by bbenligiray** [api3dao/old-api3-docs#611]
The Beacon IDs page (https://docs.api3.org/beacon/v0.1/reference/beacon-ids.html) mentions `beaconId`s and `templateId`s, then lists a bunch of hashes with no description of what they are. If I didn't know, I wouldn't be sure that the hexadecimal thing is the beacon ID because I don't know what a beacon ID looks like or if those are template IDs. Also, it's not documented what template is used to create each beacon, which makes the beacon parameters meaningless by themselves.

**Comment by wkande** [comment]
@bbenligiray Adding a cable probably is best for the Beacon ID.

> Beacon ID: 0x44407753c8ffd478e377af11067a1619dfe5bb810fd4d0265e601574f4fc0a06

Should we add the template ID in the same area as the decodeParamters hidden display are? Seems to be something the reader the user will get confused by if all they care about is the Beacon ID.

**Comment by bbenligiray** [comment]
> Adding a cable probably is best for the Beacon ID.

I think so

I guess we can just remove all references to templates from that page and only have the decoded parameters and let the user dig through the operations repo if they want to get more information.

It's actually strange how it works at the moment because the `decodedParameters` that are displayed actually belong to the respective template, rather than the beacon. But it's fine because the hackathon beacons each have a different template and all parameters are defined in the template, so the beacon-specific parameters are empty anyway. So we don't need to do anything about this with the current setup.
