### ISSUE TITLE
Enhance the relayMetadata documention

### ISSUE THREAD

**Issue by wkande** [api3dao/old-api3-docs#640]
`relayMetadata` is likely going to be the most popular security scheme for API providers. The integration team would like more details added to the docs to enhance the relay metadata flow.

**Comment by dcroote** [comment]
We could also add a link to the `airnode-examples` integration: https://github.com/api3dao/airnode/tree/master/packages/airnode-examples/integrations/relay-security-schemes

**Comment by camronh** [comment]
Vinny from the integration team did a write up on relay metadata security schemes:

https://docs.google.com/document/d/1gZ5weN9ubL4PVzST_vGhI-nIGsnPU47KKZnvPXdZu18/edit?usp=sharing

**Comment by wkande** [comment]
This has been completed and deployed. 

**Pull Requests:**
- [**656**](https://github.com/api3dao/api3-docs/pull/656)
- [**657**](https://github.com/api3dao/api3-docs/pull/657)
