### ISSUE TITLE
Specify environment variable name limitations

### ISSUE THREAD

**Issue by bbenligiray** [api3dao/old-api3-docs#73]
`envName` fields under `environment` can only include uppercase, numerical or `_`. https://github.com/api3dao/api3-docs/blob/main/docs/next/technology/deployment-files/config-json.md#environment should be updated to reflect this.

**Comment by wkande** [comment]
I did do some work on this but am holding off closing it until we decide if the providerNames can retain any dashes (-) in the `envName`. I would say not but wanted to verify.

```json
{                               
 "chainType": "evm",            
 "chainId": "1",               
 "name": "infura-ropsten",
 "envName": "CP_EVM_1_INFURA-ROPSTEN"
},
```

**Comment by bbenligiray** [comment]
I think here
https://docs.api3.org/next/technology/deployment-files/config-json.html#environment
"spaces in the names are replaced with underscores" should be "unsupported characters (whitespace, dash, etc.) are replaced with underscores"
(also the `ss` in  `ss_${oisTitle}_${name}` should be capitalized)

**Comment by wkande** [comment]
Now reads as:

---

### evnName

The value of the `envName` field is the actual environment variable name that must exist in secrets.env. The recommended naming conventions are below. Replace any unsupported characters (whitespace, dash, etc.) with underscores. All characters are uppercase.

> Supported characters; (A-Z, 0-9, _)

- chainProvider[n].envName -- `CP_${chainType}_${chainId}_${name}`
- securitySchemes[n].envName -- `SS_${oisTitle}_${name}`
