### ISSUE TITLE
Medium post list is outdated

### ISSUE THREAD

**Issue by bbenligiray** [api3dao/old-api3-docs#78]
Non-partnership Medium posts should be added to the list regularly. I'm not sure what the workflow for this should be.

**Comment by wkande** [comment]
The only workflow I can think of is that I check these weekly. If you announce to the team that a new medium post has been published that helps as well. Normally I think you are doing that. I will get these up-to-date.

**Comment by wkande** [comment]
The list of non-partnership posts has been added.
