### ISSUE TITLE
Check for broken hyperlinks

### ISSUE THREAD

**Issue by andreogle** [api3dao/old-api3-docs#8]
We should use a tool for validating that all hyperlinks are still valid.

A quick google search found this: https://github.com/tcort/markdown-link-check which actually also has Github actions integration: https://github.com/gaurav-nelson/github-action-markdown-link-check

There may be other, more suited tools out there - this was just the first one I found.

**Comment by bbenligiray** [comment]
This works pretty good, added it and fixed a bunch of broken links.

**Comment by andreogle** [comment]
Awesome. We can probably also add this to airnode later too

**Comment by andreogle** [comment]
Figured I might as well do it now or it might get forgotten

Added here: https://github.com/api3dao/airnode/commit/406619522b7413dbe8245b896d82222419197393
