### ISSUE TITLE
Improve the visibility of mnemonic in `generate-mnemonic` command

### ISSUE THREAD

**Issue by amarthadan** [api3dao/old-api3-docs#823]
Documentation changes for https://github.com/api3dao/airnode/issues/1192

**Comment by amarthadan** [comment]
~Blocked by https://github.com/api3dao/api3-docs/issues/824~

**Comment by martinkolenic** [comment]
Hi, @amarthadan and @wkande,I see the changes live and the example output looks the way it's supposed to, i.e. the mnemonic is sandwiched between the hash characters.
