### ISSUE TITLE
Add `v0.8` version of docs

### ISSUE THREAD

**Issue by amarthadan** [api3dao/old-api3-docs#824]
Since we've started working on 0.8 features it would be nice to have v0.8 version of docs where we can introduce changes.

**Comment by wkande** [comment]
This is completed PR: https://github.com/api3dao/api3-docs/pull/832

**Comment by martinkolenic** [comment]
Hi @wkande, I've just given the test site a run; when you add /v0.8 to the address, it actually points you to the new version docset, meaning it works as intended :) I'm moving this from Testing to Done but if you want me to test something particular in the docset, feel free to ping me.
