### ISSUE TITLE
Fix page flickering for the docs redirect

### ISSUE THREAD

**Issue by amarthadan** [api3dao/old-api3-docs#826]
When one accesses the https://docs.api3.org/airnode/ URL to access the latest docs there's a brief flicker showing the 404 page before redirecting.

**Comment by wkande** [comment]
This is low priority until I get a better hold on ChainAPI.

**Comment by wkande** [comment]
@Siegrift You sure you want to work on this? Here is the history.
- We started out using a plugin. Was not able to find a new plugin.
- Aaron wrote some code to avoid the plugin's limitations.
- I had to change Aaron's code in enhance.js to get the redirects to work.

**Comment by dcroote** [comment]
Three PRs / discussions related to what Warren mentioned:
- https://github.com/api3dao/api3-docs/pull/651
- https://github.com/api3dao/airnode/pull/891
- https://github.com/api3dao/airnode/pull/901

**Comment by Siegrift** [comment]
So far I've tried many approaches and none of them workws, leaving the current solution the best. Things I tried using:
- Use symlinks called `latest` to point to the folder with latest version
- https://github.com/vuejs/vuepress/issues/1803#issuecomment-602783264
- https://github.com/vuejs/vuepress/issues/239#issuecomment-384269121
- https://github.com/vuejs/vuepress/issues/239#issuecomment-711225196

What's even more unfortunate is that the issue only appears when you build the docs and serve them via a simple server. When you use the dev-server there is no 404 flickering. You apparently can't disable minification either (https://github.com/vuejs/vuepress/issues/1993) so this makes it hard to debug... I'll try to think about a solution outside vuepress redirects.

**Comment by Siegrift** [comment]
EDIT: Found a possible solution using https://vuepress-community.netlify.app/en/plugins/dehydrate/#nossr will test it and create a PR if applicable.

**Comment by wkande** [comment]
I was going to explore writing a plugin. When the solution in `enhanced.js` was written it was problematic to do redirects  properly without going through VuePress and its 40 implementaiton. I am not going to go there until you exhaust all of your findings.

**Comment by Siegrift** [comment]
The linked PR seems to be working fine (for both me locally and the preview site).

**Comment by wkande** [comment]
@kolenic-martin Don't know if you want to test this. I tried it and everything seems good. It has been published to `docs.api3.org`

**Comment by dcroote** [comment]
@wkande - I don't see the 404 flash on preview site from @Siegrift's PR, but I do for the live docs.api3.org site. I'm testing with and/without opening the link in an incognito window. For comparison:
- https://docs.api3.org/airnode/latest/introduction/why-use-airnode.html 
- https://api3-docs--fix-404-odrstf7b.web.app/airnode/latest/introduction/why-use-airnode.html

**Comment by Siegrift** [comment]
Yeah, happens for me as well. I am not sure how you do the release, but make sure you do `npm i` (to install the plugin). Also, I was able to test this locally by following https://docs.api3.org/dev/link-validator.html#step-2-start-http-server

Can you confirm it works for you when you serve the built files locally?

**Comment by martinkolenic** [comment]
I can confirm @Siegrift's and @dcroote's issue too. I also see the 404s for a tiny moment. Not happening on the previews, though.

**Comment by wkande** [comment]
@kolenic-martin @dcroote . Please try it again.

**Comment by Siegrift** [comment]
I confirm this works from the user perspective.

However it's still not enough to resolve https://github.com/api3dao/ois/issues/3 because the docs requests to `/latest` on CI still fail with 404... I've confirmed this via Postman which also reports 404. I think the problem is that the redirect is client side only which of course doesn't work for non browser requests.

That being said, I don't think it's a a big deal and I'd rather use similar solution to https://github.com/api3dao/airnode/pull/901 instead of spending more time on this.

**Comment by dcroote** [comment]
It's working for me from a user perspective as well. I also agree with @Siegrift- the main goal of preventing users from seeing 404 pages is accomplished and the CI fix isn't so much an issue to warrant additional effort.
