### ISSUE TITLE
Add link to nodeVersion in component

### ISSUE THREAD

**Issue by wkande** [api3dao/old-api3-docs#829]
Add a link to the first occurrence of `nodeVersion` in the component `DockerImageVersions`. Link it to Deployments > `config.md`. Use the Vue router tag in the HTML template.

**Comment by wkande** [comment]
Component updated and moved to the `/airnode` folder. 

PR https://github.com/api3dao/api3-docs/pull/836

**Comment by wkande** [comment]
@kolenic-martin All I did was move the component and added a link to it. You can see it here. Look for the first link on the word `nodeVersion`.

https://docs.api3.org/airnode/v0.8/grp-providers/docker/#dockerhub
https://docs.api3.org/airnode/v0.7/grp-providers/docker/#dockerhub
https://docs.api3.org/airnode/v0.6/grp-providers/docker/#dockerhub

**Comment by martinkolenic** [comment]
Thanks, @wkande, I've checked that and it seems to be working just fine for all three versions you've mentioned.
