### ISSUE TITLE
dAPIs: Last 5 transactions values incorrect

### ISSUE THREAD

**Issue by wkande** [api3dao/old-api3-docs#831]
The API operation for the last 5 transactions seems to be returning the same value each time it is called regardless of the dAPI reqested.

**Comment by wkande** [comment]
@aquarat is looking into the API operation `https://api.api3data.link/beacons/last_transactions`. I think it is returning the same payload for all pairs.

**Comment by aquarat** [comment]
The bug has been resolved; the API Gateway caching was incorrectly configured (it is part of an uncommitted file). The result of the missing configuration was that the API gateway was caching responses without considering the dapiName (`dapiName` was not part of the cache keys).

The example configuration in the beacons-api repository is correct, so no PR will be created for this.

Thanks for reporting @wkande :smile:

**Comment by wkande** [comment]
@kolenic-martin @aquarat - Martin this seems to be working now. I think the only test is to click on each dAPI to veryify the last 5 transactions are in range with the current value.

https://docs.api3.org/dapis/reference/dapi-browser.html

**Comment by martinkolenic** [comment]
Hi @wkande, sorry for the late reply but I've gone through the dAPIs and they do show values the way they are supposed to, i.e. within range. It looks quite nifty by the way.
