### ISSUE TITLE
Add hardcoded whitelisting into the config file

### ISSUE THREAD

**Issue by amarthadan** [api3dao/old-api3-docs#842]
Documentation for https://github.com/api3dao/airnode/issues/1197

**Comment by martinkolenic** [comment]
Hi @amarthadan, when creating docs issues, please add the Documentation label to it so it's immediately clear what's what. Thanks.

**Comment by amarthadan** [comment]
@kolenic-martin You can see that by the repository where the issue resides.
![Screenshot_20220706_133956](https://user-images.githubusercontent.com/1655405/177542096-10e7a7fb-6de4-4835-8fc3-ba712e612dbd.png)
You can also filter the board by the repository if you need.

**Comment by martinkolenic** [comment]
@amarthadan that's a good point, thanks. Although, why do we have that label in the first place when we're not using it?

**Comment by amarthadan** [comment]
In the Airnode repo? Just historical reasons I guess. That will be (hopefully) cleaned up at some point.
