### ISSUE TITLE
Automatically remove unsuccessful Airnode deployments

### ISSUE THREAD

**Issue by amarthadan** [api3dao/old-api3-docs#853]
Documentation for https://github.com/api3dao/airnode/issues/1188

**Comment by Siegrift** [comment]
What's there to document?

**Comment by amarthadan** [comment]
The behavior itself. It should be noted in the documentation that when the deployment fails we automatically try to remove it and the reasoning behind it. Also, I presume (I haven't checked the implementation yet) that there's a new CLI option to turn this off.

**Comment by Siegrift** [comment]
> that there's a new CLI option to turn this off.

Yeah, working on that now, but I am not sure it even needs to be mentioned in docs. I consider that flag dev-only to make it possible to test/debug stuff.

> It should be noted in the documentation that when the deployment fails we automatically try to remove it and the reasoning behind it

Fair enough.

**Comment by amarthadan** [comment]
> Yeah, working on that now, but I am not sure it even needs to be mentioned in docs. I consider that flag dev-only to make it possible to test/debug stuff.

AFAIK we're putting the output of the help command to the docs and that will include the flag. As it does for the `--debug` one.

**Comment by wkande** [comment]
Could I get some clarity on this. Is default behavior of the Docker image for `v0.8` to remove the deployment if it fails? Can this be configured when using Docker?

**Comment by Siegrift** [comment]
> Could I get some clarity on this. Is default behavior of the Docker image for v0.8 to remove the deployment if it fails? Can this be configured when using Docker?

Yeah, it can. I've created a draft PR for you https://github.com/api3dao/api3-docs/pull/860/files

**Comment by martinkolenic** [comment]
I've done a quick read-through of the related docs sections and fixed minor typos that I found, so I think otherwise this is good to go after my PR is merged.
