### ISSUE TITLE
Example heartbeat API operation

### ISSUE THREAD

**Issue by wkande** [api3dao/old-api3-docs#863]
Create an example endpoint that an Airnode might call as its heartbeat callout. This code snippet should go into the `heartbeat.md` file go _Configuring and Airnode_.

**Comment by amarthadan** [comment]
If this is just for testing purposes you can suggest using services like https://beeceptor.com/ and/or https://webhook.site that can create temporary endpoints for you.

**Comment by wkande** [comment]
Those might work. This is on the back burner for now.

**Comment by dcroote** [comment]
I used httpbin.org for the the relay security schemes example integration and it seems to work well: https://github.com/api3dao/airnode/tree/master/packages/airnode-examples/integrations/relay-security-schemes

**Comment by wkande** [comment]
Determined that this was not needed.
