### ISSUE TITLE
Add OIS `v1.1` doc set

### ISSUE THREAD

**Issue by wkande** [api3dao/old-api3-docs#869]
We seem to need a new version for the OIS doc set. Should it be `v1.1.1` or `v1.1` doc set. See the discussion [here](https://github.com/api3dao/api3-docs/pull/858).

OIS versions:
v1.0 - used for Airnode versions <= 0.7
v1.1 - used by Airnode 0.8

**Comment by wkande** [comment]
This will involve refactoring `v1.0.0` to `v1.0`.

**Comment by wkande** [comment]
PR: https://github.com/api3dao/api3-docs/pull/876

**Comment by martinkolenic** [comment]
Hi @wkande, I looked at this earlier in the day and it looks just fine to me, both v1.0 and v1.1 are accessible and I have no complaints content-wise. Moving this to Done then.
