### ISSUE TITLE
Expand search across multiple doc sets

### ISSUE THREAD

**Issue by wkande** [api3dao/old-api3-docs#872]
Add new tabbed panes to the search results pop-up window.

1. The left most tab will show results for the doc set the reader is viewing. Currently this is the only view.
2. The middle tab will show results for all versions of the doc set the reader is viewing. This tab will not appear if the doc set in not versioned.
3. The right most tab will show results for all docs current doc set, meaning the latest version (for version doc sets) and the other non-versioned doc sets.

The third option might be better if the search was across all docs set and versions.

**Comment by wkande** [comment]
A better approach might be to have a checkbox to search across all doc set rather than the current doc set.

update: 8-2: Going with two tab, the current docs set and all doc set.

**Comment by wkande** [comment]
@dcroote @kolenic-martin - Can you look at this **[preview](https://api3-docs--pr952-872-search-all-doc-s-v3b7vq2z.web.app/)** for the search. This PR was only to allow for a search across all doc set as well as to switch between doc sets within the search overlay. There are about four additional enhancements to search but those will be other GitHub issues.PRs.

**Comment by martinkolenic** [comment]
Hi @wkande, I've tried switching between individual docsets and leaving "All Documentation" option on and it works flawlessly. I noticed the search is also significantly faster.

**Comment by dcroote** [comment]
Agreed- works nicely! Can the order of results be changed for "All Documentation"? My thought is to have it in reverse-chronological order for Airnode results: v0.7 at the top, then v0.6, v0.5, etc. rather than currently starting with pre-alpha at the top.

**Comment by wkande** [comment]
@kolenic-martin and @dcroote  

I will create a new issue for the **sort** thing. That will be a messy function. Then the sort issue will probably be the last change for the "search" in these docs sets. I have other ideas for the search but after today's meeting and the talk about a new documentation set I'm thinking to hold off on such improvements for the current documentation. 

The search currently has to deal with the versioning of Airnode and OIS and that is messy with the current documentation. If we go to a focused based documentation site I thing the versions need to be rolled in differently and in my mind that seems to be possible, just not sure what it would look like yet.

Anyway I am going to merge this bad boy. Thanks.

**Comment by dcroote** [comment]
Thanks @wkande. I would say the sort is a low priority convenience, if it's too complicated I wouldn't worry.

**Comment by amarthadan** [comment]
I noticed that this issue is in the `Done` column but is still open. Can it be closed?

**Comment by martinkolenic** [comment]
I'm okay with this being closed but I thought that I should leave this up
to Warren.

Dňa št 11. 8. 2022, 11:05 Michal Kimle ***@***.***>
napísal(a):

**Comment by wkande** [comment]
@amarthadan and @kolenic-martin  - Closing this issue.
