### ISSUE TITLE
Docker image mention auto-remove

### ISSUE THREAD

**Issue by wkande** [api3dao/old-api3-docs#875]
Mention the auto removal of a failed deployment in `https://docs.api3.org/airnode/v0.8/grp-providers/docker/deployer-image.html`.

**Comment by wkande** [comment]
@aquarat @amarthadan 

Just for clarity.

1. By default (for a new deployment) the docker image will attempt to auto-remove the deployment should it fail?

2. If the deployment already exists and I try to deploy again (update it) and it fails will it revert or delete the deployment? Not sure updating is even possible to begin with.

**Comment by amarthadan** [comment]
> Just for clarity.
> 
>     1. By default (for a new deployment) the docker image will attempt to auto-remove the deployment should it fail?

Yes. 

>     2. If the deployment already exists and I try to deploy again (update it) and it fails will it revert or delete the deployment? Not sure updating is even possible to begin with.

That's a good question. I would presume so. @Siegrift did the implementation, he will know. Is that a problem? If the redeployment failed there's a possibility that whatever is deployed might be in an inconsistent state.

**Comment by Siegrift** [comment]
> If the deployment already exists and I try to deploy again (update it) and it fails will it revert or delete the deployment? Not sure updating is even possible to begin with.

Yes, it will attempt a removal. Deployer does not differentiate between update and deploy so both behave the same.
