### ISSUE TITLE
QRNG docs assume an EOA sponsor, while qrng-example has the requester sponsor itself

### ISSUE THREAD

**Issue by bbenligiray** [api3dao/old-api3-docs#881]
See https://discord.com/channels/758003776174030948/765618225144266793/994593770509189131

In the context of qrng-example, sponsor and requester addresses are the same for simplicity. The docs have the user generate a sponsor mnemonic, which is not needed. This may be why QRNG users have been confused about the sponsorship scheme. The docs need to be updated to match qrng-example. Alternatively, strip the docs down and rely on qrng-example more heavily.

**Comment by wkande** [comment]
This has resulted in major changes to the QRNG docs. See the **[preview site](https://api3-docs--881-qrng-sponsorwallet-is-requestor-address-8u27es5o.web.app/)**.

1. New sub-sections added to the sidebar.
2. The QRNG sample project is now a first-class-citizen in the sidebar under "Guides".
3. A new "Remix Example" page added to the guides section.
4. Added the Youtube video to the guides section.
5. Added a new sidebar section "Reference".
6. Added both the `QrngExample.sol` and `RemixQrngExample.sol` contracts to the reference section.

@bbenligiray @Ashar2shahid @dcroote @kolenic-martin 

Some comments on the **[Remix Example](https://api3-docs--881-qrng-sponsorwallet-is-requestor-address-8u27es5o.web.app/qrng/guides/remix-example.html)** would be useful. Do we keep it, change anything in it? I was thinking of doing another Remix example for dAPIs as I had heard in a meeting it might be nice to have an example for dAPI calls.

**Comment by wkande** [comment]
@kolenic-martin This PR introduces a restructuring of the QRNG docs. The only new "thing" is the **Remix Example**. I have tested it and think it works well but a second set of eyes is always useful. Let me know if you need and guidance. It uses a combinations of the Remix IDE and CLI.
