### ISSUE TITLE
Move cloud auth files into the `config` directory

### ISSUE THREAD

**Issue by amarthadan** [api3dao/old-api3-docs#892]
Documentation for https://github.com/api3dao/airnode/issues/1329

**Comment by wkande** [comment]
@kolenic-martin I am in process of updating the tutorial zip file for this change as well. You will see it come across in GitHub issue https://github.com/api3dao/api3-docs/issues/900

**Comment by martinkolenic** [comment]
Hi @wkande, I've checked the preview site but I do not seem to see the changes - everything is supposed to be in the root directory, correct?

![image](https://user-images.githubusercontent.com/884979/179921649-0b14c789-8e45-4ec6-8ad1-2c733b93d796.png)

![image](https://user-images.githubusercontent.com/884979/179921705-22ebd227-dd88-4267-b0eb-65354a66936d.png)

**Comment by dcroote** [comment]
@kolenic-martin those screenshots are from v0.7 Airnode not v0.8

**Comment by martinkolenic** [comment]
That was the preview site, which only has v0.7 as the latest version, the
live version seems fine now that I checked. Sorry about the confusion.

Dňa st 20. 7. 2022, 9:24 Derek Croote ***@***.***> napísal(a):

**Comment by dcroote** [comment]
> That was the preview site, which only has v0.7 as the latest version

It's true that v0.7 is the latest on the preview site, but for testing it does have v0.8, you just have to edit the URL manually in the address bar.

**Comment by martinkolenic** [comment]
Tbh that is not the most intuitive method to test but you're right, I don't
know why I didn't realize that before since I'd done that previously.
Morning brain I guess.

Dňa st 20. 7. 2022, 9:32 Derek Croote ***@***.***> napísal(a):
