### ISSUE TITLE
CloudFlare doc hosting?

### ISSUE THREAD

**Issue by wkande** [api3dao/old-api3-docs#893]
Take a look at CloudFlare to host the docs. There may be a better solution for redirects. It can build directly from the repo as well.

**Comment by wkande** [comment]
@aquarat Are we thinking to still try CloudFlare? I saw a conversation you had with Emanuel and then you removed the CloudFlare build from the docs repo. Have you decided it is not worth it?

**Comment by dcroote** [comment]
There were a couple times where I saw the cloudflare build fail but firebase build was fine. I tried to see the reason but it was hidden behind a cloudflare login screen. 🤷‍♂️

**Comment by aquarat** [comment]
Ah, yes, sorry, Emanuel kind of defused the idea and at the time no one else had commented, so I turned off the integration. I should have probably asked.
Cloudflare Pages got better scores on Google Page Insights compared to the current solution, but it still delivered 404s for non-existent pages (although the payload of the response was the site's JS). Cloudflare Pages does support a dedicated redirects file, but I don't know if that changes the status codes for "non-existent" pages or if it's useful. The current solution where it's initially a blank page (as opposed to a 404 page) works adequately imo.

I can re-enable Cloudflare builds if you like? If you'd like access feel free to create a Cloudflare account and give me your login username :)

**Comment by wkande** [comment]
@aquarat I created a CloudFlare account. Can you give me access to the "stuff"?  (warren-at-api3.org)

**Comment by aquarat** [comment]
This will have to wait till I'm back unfortunately.
The Cloudflare account needs to be linked to Github as an app. You may be able to do that through your own Github account - I'm not sure.
Then the build process needs to be configured in Cloudflare Pages. Once that's done it'll build the site and generate a preview URL.

**Comment by wkande** [comment]
@Siegrift @dcroote @aquarat 

Today I testing CloudFlare redirects by setting up a "redirect list" which is a little confusing but doable. I create a dummy doc site with a few pages using VuePress 2x (we are currently using 1x). This dummy site has no internal redirect code in it. You shoot it a bad URL it gives you a 404. The CloudFlare redirects behave as you would expect. If you sent it [/latest/](https://vuepress-9jh.pages.dev/reference/) you get the correct page because the SPA loads initially using a valid page as sent by CloudFlare (https://vuepress-9jh.pages.dev/reference/deployment-files/config-json.html ).

The downside seems to be the cost. I am using the free plan and it does not give you much.

![Image](https://user-images.githubusercontent.com/3522283/184727746-31584622-64c1-42b1-b32b-c41912a60ba9.png)

So you only get 20 redirects and that really is 10 if you want to cover things like the following (because they are different.):

.../latest
.../latest/

I think the expense could escalate quickly. The service work great.

**Comment by Siegrift** [comment]
When you make a request to `latest` (e.g. https://docs.api3.org/airnode/latest/) from postman or CURL, what is the HTTP response you get? Because the problem we have with the redirect is that they are client side only and these requests return 404 which breaks the markdown checkers.

What is the additional improvement of using cloudflare and its redirects? I thought we [agreed on Slack](https://api3workspace.slack.com/archives/C02AYRX8D89/p1658480886915059?thread_ts=1657800795.304029&cid=C02AYRX8D89) not to pursue this.

**Comment by wkande** [comment]
```
curl https://vuepress-9jh.pages.dev/latest/ -v
...
> 
* Connection state changed (MAX_CONCURRENT_STREAMS == 256)!
< HTTP/2 301 
< date: Tue, 16 Aug 2022 13:18:00 GMT
< location: https://vuepress-9jh.pages.dev/reference/deployment-files/config-json.html
< cache-control: max-age=3600
< expires: Tue, 16 Aug 2022 14:18:00 GMT
```
Since the GET request goes to CloudFlare they send the redirect to the browser and of course it returns to CloudFlare as expected to get the new location, and then the SPA loads.

**Comment by wkande** [comment]
Is it still a concern? yes. The previous evaluation mentioned on Slack was incorrect. I do not think it was set up correctly. But due to the cost this might not be worth it. Perhaps there is a more cost effective service that does the same. @dcroote - do you know if Firebase has a redirect "module"?

**Comment by wkande** [comment]
Apparently Firebase does all for redirect in `firebase.json`. https://www.youtube.com/watch?v=Vt08efzophA

**Comment by wkande** [comment]
I did a quick test with Firebase and it seems to work well and is free. I am going to close this task and create a new one around Firebase.

**Comment by Siegrift** [comment]
If you can improve the current way redirects work it will be nice. However, the issue with 404 still persist when you call the `latest` (so we still have to use the trick for the CI)

<img width="1109" alt="image" src="https://user-images.githubusercontent.com/22679154/185034911-3897a50e-9204-4b55-bd59-584ac4f8c641.png">

**Comment by wkande** [comment]
@Siegrift Try ` curl -v https://vuepress-9jh.pages.dev/latest/` and not ` curl -v https://vuepress-9jh.pages.dev/latest`. ClouldFlare is picky. I only created a redirected for the former and not the latter. Firebase does not have this issue.
