### ISSUE TITLE
Relocate gasPriceOracle strategies in `config-json.md`

### ISSUE THREAD

**Issue by wkande** [api3dao/old-api3-docs#896]
In the file `reference/deployment-files/config-json.md` we need to relocated the `strategies`: latestBlockPercentileGasPrice, providerRecommendedGasPrice and constantGasPrice to be under `gasPriceOracle` as possible strategy values.

**Comment by wkande** [comment]
Also check other files that mention gasPriceOracle and strategies.

**Comment by wkande** [comment]
@vponline What do you think about a new page under **Concepts and Definitions** maybe called **Gas Prices** or **Oracle Gas Prices**. It does seem to be something that has grown into a item of importance.

**Comment by vponline** [comment]
> What do you think about a new page under Concepts and Definitions maybe called Gas Prices or Oracle Gas Prices. It does seem to be something that has grown into a item of importance.

I think that's a great idea. Perhaps just referring to `Gas Prices` (strategies) would be better than using the `oracle` term since they are just different ways to calculate the gas price to use.

I'd be happy to help with this as well so please let me know.

**Comment by vponline** [comment]
Thanks @dcroote for mentioning that the `chain-idiosyncrasies.md` page (#895) that should be updated to handle these strategies as well.

I am not entirely sure how these strategies should be used on these chains, though. Should we be setting the `txType` for each strategy separately, or applying a specific (i.e. the EIP1559) strategy for those that don't work with the default `legacy` transactions. :thinking:

**Comment by wkande** [comment]
@vponline @dcroote I am going to create two new issues as this one seems to be expanding.

1. `chain-idiosyncrasies.md` > gas price strategies.
2. `gas-prices.md` a new file in Concepts and Definitions, again about gas price strategies.

I do not understand the **gas price strategies** so will need someone else to write these. I can follow-up and learn from the docs and then do additional work if needed.

**Comment by vponline** [comment]
Thanks @wkande. It's probably best if these are assigned to me and then you could review them. So please feel free to assign them to me (or they can be assigned tomorrow on the call)
