### ISSUE TITLE
Add more warnings about designated wallets

### ISSUE THREAD

**Issue by bbenligiray** [api3dao/old-api3-docs#9]
The designated wallets are [custodial](https://github.com/api3dao/api3-docs/blob/master/request-response-protocol/designated-wallet.md#the-custodial-nature-of-the-designated-wallets), meaning that the requesters should be keeping only as much ETH as they trust the provider with.
Add more warning about this, refer to [this example](https://github.com/api3dao/airnode-client-examples/issues/2) when it's implemented.

**Comment by wkande** [comment]
I have created a Vue component that displays a designated wallet warning in four places, (1) in **/pre-alpha** and (3) in **/next**. 

I am not sure if the work done here satisfies the issue. Not sure what the example referred to is all about.

Not closing this issue until @bbenligiray reviews this it again.

**/pre-alpha**

- https://docs.api3.org/pre-alpha/protocols/request-response/designated-wallet.html

**/next**

- https://docs.api3.org/next/grp-requesters/become-a-requester.html
- https://docs.api3.org/next/grp-requesters/fees.html
- https://docs.api3.org/next/reference/protocols/request-response/designated-wallet.html

**Comment by wkande** [comment]
Closing this issue. It has been 30 days and the vue component is doing its job.
