### ISSUE TITLE
Validate tutorial zip files for `v0.8`

### ISSUE THREAD

**Issue by wkande** [api3dao/old-api3-docs#900]
This is related to PR https://github.com/api3dao/api3-docs/pull/899 as a follow-up. The tutorial zip files for `v0.8` need to be verified.  @kolenic-martin They cannot be tested as the docker image  `v0.8.0` is not available yet

I will work on this issue right after merging the fore-mentioned PR.

**Comment by wkande** [comment]
@kolenic-martin This is ready. I think the only test is to verify that the downloaded files have the proper directory structure changed by @dcroote . I downloaded them and they look good to me.

**Comment by dcroote** [comment]
I confirmed the 3 zip files have the expected flat directory structure, moving to Done.

**Comment by martinkolenic** [comment]
Hi @dcroote, I preiously had some issues (the zip files were not updated in the preview site) but that was probably something on my side.

**Comment by dcroote** [comment]
@kolenic-martin - oh strange, perhaps it was an issue with the preview site? I confirmed on the live  docs.api3.org site under Airnode v0.8.

**Comment by martinkolenic** [comment]
Ah, yes; this was probably an issue with the preview. The other issue (892)
seems to exhibit the same problem.

Dňa st 20. 7. 2022, 9:23 Derek Croote ***@***.***> napísal(a):
