### ISSUE TITLE
Add market.api3.org to dAPIs doc set

### ISSUE THREAD

**Issue by wkande** [api3dao/old-api3-docs#904]
Somewhere the URL `market.api3.org` needs to be added to the dAPIs doc set.

**Comment by wkande** [comment]
This task will also expose the dAPIs doc set on the landing page and the sidebar as the API3 Market is now live.

**Comment by wkande** [comment]
@kolenic-martin Not much to test here. All links passed link-checker. I did click on the new API3 Market links to validate them manually.

**Comment by martinkolenic** [comment]
Hi @wkande, I just looked at it for good measure and this works without any problems. Moving to Done.
