### ISSUE TITLE
Remove Google Cloud SDK mentions from the docs

### ISSUE THREAD

**Issue by amarthadan** [api3dao/old-api3-docs#908]
[This section](https://docs.api3.org/airnode/v0.7/grp-providers/tutorial/quick-deploy-gcp/#install-prerequisites) (and maybe some others) says that the Google Cloud SDK needs to be installed in order to run GCP tutorial. That's not true anymore (since 0.4 actually).

**Comment by wkande** [comment]
I will take care of this for all versions. @amarthadan does this include `v0.4` and above? You said since `v0.4` so I want to be sure.

Duh never might I see your tags now.

**Comment by wkande** [comment]
@kolenic-martin Nothing to test here.

**Comment by martinkolenic** [comment]
Hi @wkande, in these cases, feel free to move this straight to Done next time. I've checked that just to have a second pair of eyes on it and it LGTM.
