### ISSUE TITLE
maxConcurrency example has typo(s) and needs clarification

### ISSUE THREAD

**Issue by dcroote** [api3dao/old-api3-docs#912]
Reported by a user in Discord: https://discord.com/channels/758003776174030948/765618225144266793/999327698033844394

1. It looks like it should be `C1` instead of `C2` in the sentence: `The above example results in the following requests: A1, A2, B1, B2 and C2.`
2. This part is confusing: `but this is still not enough to meet the limit so request C2 is dropped as well.`
3. What mechanism exists to prevent all 5 provider A requests from being fulfilled and none of B and C? Will this hold true if all 5 provider A requests have an earlier timestamp than any of B or C or does that not matter?

https://github.com/api3dao/api3-docs/blob/0172e1b0710322c90998ed7b81221c3e0b7f9efc/docs/airnode/v0.7/grp-providers/guides/build-an-airnode/configuring-airnode.md?plain=1#L139-L148

**Comment by dcroote** [comment]
@Siegrift it looks like this was added in #536

**Comment by Siegrift** [comment]
1. Yeah, there is a typo. The C1 gets fulfilled first.
2. I think we can drop that sentence.
3. Not sure what `What mechanism exists to prevent all 5 provider A requests from being fulfilled and none of B and C?` means. The timestamps do not matter, the idea behind request dropping is to make sure a malicious provider will not be able to congest Airnode by too many request (leading to no requests being made). That's we the strategy is to take the oldest requests across all the providers.

**Comment by dcroote** [comment]
> That's we the strategy is to take the oldest requests across all the providers.

Ok to make sure I understand: Airnode processes the oldest single request per provider and repeats that until either all requests are processed or the maxConcurrency is hit?

**Comment by Siegrift** [comment]
Not really. The request filtering happens before any request is attempted.

**Comment by dcroote** [comment]
Ah yes sorry poor choice of word- I meant Airnode filters requests by looping through providers, retaining the oldest single request per provider, until either all requests are included or the maxConcurrency is hit?

**Comment by Siegrift** [comment]
Yes, that's correct.
