### ISSUE TITLE
`dapiNameHash` not computed correctly

### ISSUE THREAD

**Issue by wkande** [api3dao/old-api3-docs#919]
The "TIP" block on `/dapis/developers/reader-can-read-datafeed.md` needs three corrections.

<img width="826" alt="readerCanReadDataFeed" src="https://user-images.githubusercontent.com/3522283/180490089-b400b34d-5e7f-43e2-b42b-e63c1992a035.png">

#### #1
Assuming `dapiName` is a `string`, then the following is wrong:
`dapiNameHash = ethers.utils.solidityKeccak256(['string'], [dapiName]);`

And should be:
`dapiNameHash = ethers.utils.solidityKeccak256(['bytes32'], [ethers.utils.formatBytes32String(dapiName)])`

#### #2 
"**dAPI `name`**" should be `dapiName`.

#### #3 
In the code example the function called is `readerCanReadDataFeed()`. The is some garbage if the function name. Probably from a copy/paste action.

**Comment by wkande** [comment]
@kolenic-martin There were several issues with the code comments and samples on this page. I think they are cleaned up now. So nothing to test, maybe just a second set of eyes. Thanks.

See https://docs.api3.org/dapis/developers/reader-can-read-datafeed.html

**Comment by martinkolenic** [comment]
Hi @wkande, I'm on vacation till July 31, so I can look at it then but if
this is urgent, perhaps there will be someone else who'll help.

Dňa so 23. 7. 2022, 21:28 Warren Anderson ***@***.***>
napísal(a):

**Comment by martinkolenic** [comment]
Hi, @wkande, I'm back and this LGTM, no problems.
