### ISSUE TITLE
Point ChainAPI router links to Airnode latest

### ISSUE THREAD

**Issue by wkande** [api3dao/old-api3-docs#922]
Should ChainAPI doc set internal links to Airnode point to `$themeConfig.latestversion.airnode`? In doing this ChainAPI would need to support new released to Airnode as they come out without delay.

**Comment by dcroote** [comment]
> ChainAPI would need to support new released to Airnode as they come out without delay

I don't anticipate this is the plan. CC @andreogle

**Comment by wkande** [comment]
I am concerned if `v0.8` will be supported by ChainAPI right away in that there are several changes. No breaking changed  that I am aware of. I want to use the new `$themeConfig.latestversion.airnode` variable for internal links in the ChainAPI doc set that point to the latest release of the Airnode doc set. This means I do not need to update ChainAPI docs every time there is a new release of Airnode.

Not sure this is a good idea right now, so for now the ChainAPI doc set needs to be updated manually until we have this discussion with ChainAPI team members. @RyanMakiola @tamra9991

**Comment by wkande** [comment]
So this:
```
[Airnode](/airnode/v0.7)
```
Would becomes this if we implemented:
```
<router-link :to="$themeConfig.latestVersions.airnode">Airnode</router-link>
```

**Comment by RyanMakiola** [comment]
@wkande I think its safe to say that its better to keep ChainAPI manual. We do not have any plans at the moment to support the latest Airnode version on ChainAPI at the same time you release it. There will be a bit of a buffer between when it is released and when it is supported by ChainAPI

**Comment by wkande** [comment]
We go with manual then.
