### ISSUE TITLE
GitHub Codespaces

### ISSUE THREAD

**Issue by wkande** [api3dao/old-api3-docs#926]
Explore codespaces in GitHub. This is being used by ChainAPI for their edits to the ChainAPI doc set. It appears to work well but two things might make it better if we can get them to work.

1. Prettier needs to be configured to run automatically on save.
2. The IDE without a codespace does not seem to allow the execution of a local dev server. This would be useful for the editor to check their work before pushing their branch work and then creating a PR.

Work on this with @RyanMakiola

**Comment by wkande** [comment]
@rlt @RyanMakiola I was looking at **github.dev web-based editor** and it does not appear to me that it can run Prettier. From what I can tell one would need to use GitHub Codespaces (and github.dev web-based editor) to do so. In your **[PR 924](https://github.com/api3dao/api3-docs/pull/924)** it looks like Richard did a separate commit after running Prettier, right after  Ryan made his changes to the sidebar and the workspaces docs.

So I see two options unless you have new ideas.

1. Continue to use **github.dev web-based editor** as you did in PR 924, with a follow-up Prettier commit.
2. Or look into GitHub codepaces, which starts to get more complicated and make cost $.

Any other thoughts or ideas?

**Comment by rlt** [comment]
Yeah I spent a few hours trying to get Ryan set up locally on his Mac but kept running into issues and had to pause. I've been wanting to pick that up again, but the codespaces solution might be the best call. The edits are relatively infrequent so the costs would probably be fine but that would need to be monitored.

**Comment by RyanMakiola** [comment]
I cleared my browser cache recently and it looks like extensions for github.dev are stored on your cache then. I installed the Prettier extension again on github.dev and made a very minor change, looks like everything passed on this PR test https://github.com/api3dao/api3-docs/pull/930

**Comment by rlt** [comment]
Just confirming, did it make some changes automatically when you saved the file?

**Comment by RyanMakiola** [comment]
Not sure, but I made a very slight change. I can make a lot more changes to a file with similar changes to what we have done before and test it again.

**Comment by rlt** [comment]
Cool - the purpose of prettier is to format the files in a consistent way automatically (according to its default rules plus any settings defined in this project) so if we can confirm it is doing that correctly with this method then I think this is good to go.

**Comment by dcroote** [comment]
> looks like everything passed on this PR test #930

To test Prettier you'll need a more substantive change than in #930. If you add or subtract several words from a line in a `.md` file that is usually enough to trigger a line break / reorganization according to the preset line character limit.

**Comment by RyanMakiola** [comment]
It failed now with the extra changes. So it's not that I need to make changes in the settings of the extension? I would have been great if it could work with github.dev

**Comment by wkande** [comment]
For it to work I am somewhat sure that github.dev must run inside a codespace.

**Comment by rlt** [comment]
Yeah that would make sense to me as well (that's why I was checking if it had actually worked)
