### ISSUE TITLE
Test GCP region and zones

### ISSUE THREAD

**Issue by wkande** [api3dao/old-api3-docs#950]
Run the GCP tutorial using just a region `us-east1` and using a region/zone `us-east1-a`. Then determine the correct terminology for the docs [**here**](https://docs.api3.org/airnode/v0.7/reference/deployment-files/config-json.html#cloudprovider-region).

**Comment by martinkolenic** [comment]
Hi @wkande, have you tested this or is this waiting on me? Thanks.

**Comment by wkande** [comment]
I don't think this needs testing, @dcroote  worked through it and resolved everything.
