### ISSUE TITLE
dAPI BBP: Security Documentation Request From Dapps

### ISSUE THREAD

**Issue by jgcogsystematictrading** [api3dao/old-api3-docs#959]
Dapps have requested more extensive documentation on our security practices similiar to [this chainlink one](https://docs.chain.link/docs/best-security-practices/) . I have started by preparing a section on failover capabilities that I think should be added to the docs.

Failover Capabilities
- Airkeeper and Airseeker run in tandem, both with the ability to update data feeds based on a deviation threshold. Airseeker runs with a slightly lower deviation threshold, meaning it’s the primary method of updating feeds with Airkeeper as the backup. An Airkeeper instance is run by each data provider and performs first party updates, while Airseeker is run by the API3DAO performing third party updates using [signed data](https://docs.api3.org/airnode/v0.7/#off-chain-data-signing), allowing them to be very responsive to issues such as an RPC failure.
- Deployments of Airnode and Airkeeper are done on both GCP and AWS instances by data providers running a Beacon to ensure uptime if one service fails.
- Data providers must use multiple proven RPC providers as parameters for the Airnode and Airkeeper deployed. Each read/write to the chain will be tried on every one of the providers RPCs.
- The API3 core technical team manages a multisig that can point DAPIs to new Beacons in case of issues with certain data providers.

**Comment by Siegrift** [comment]
> while Airseeker is run by the API3DAO (performing third party updates)

This suggest that api3 dao can misreport by changing the value that is submitted on chain. That is not possible since Airseeker calls the API providers Airnode to get the signed data and the signature is checked on chain. Api3 dao can only deny access (e.g. when Airseeker is down) but cannot misreport.

**Comment by jgcogsystematictrading** [comment]
> > while Airseeker is run by the API3DAO (performing third party updates)
> 
> This suggest that api3 dao can misreport by changing the value that is submitted on chain. That is not possible since Airseeker calls the API providers Airnode to get the signed data and the signature is checked on chain. Api3 dao can only deny access (e.g. when Airseeker is down) but cannot misreport.

I was trying to avoid repeating things stated earlier in the docs as this is explained already here https://docs.api3.org/airnode/v0.7/#off-chain-data-signing. But I can link this to the section you referenced. 

Change has been made above

**Comment by wkande** [comment]
I think at this point it might be best to write up a simple document about security. I am in the process of coming up with a Best Practices (for the use of dAPIs) and this might merge with it. Or become stand alone page in the dAPIs doc set under the the Reference section.

**Comment by wkande** [comment]
If we are not sure what to write we can start with a list on concerns, the list of four above are a good start but are there more?

**Comment by jgcogsystematictrading** [comment]
> If we are not sure what to write we can start with a list on concerns, the list of four above are a good start but are there more?

Yes that was just the start I can build on that. I agree this seems to fit under your dAPIs best practice issue so I will move dicussion there to consolidate.

**Comment by KCorstor** [comment]
Hi guys, thanks for working on all of this. In addition to the points you mentioned, I think there was some concern about best practices for repo control on AWS Lambda. Not really my area of expertise but thought I'd mention it.

**Comment by wkande** [comment]
@KCorstor Can you offer more detail about what you mean `about best practices for repo control on AWS Lambda`?

**Comment by umersin61** [comment]
How feeds are operated is an entirely different thing than implementation best practises. 

Consolidating that makes no sense, since one is an implementation guide/suggestion and another is a security/operations documentation. 

These will be treated separately.

**Comment by bbenligiray** [comment]
Should this be closed?

**Comment by KCorstor** [comment]
@wkande, @bbenligiray I think this was back when we were pitching single-sourced feeds. Someone was curious about security in regards to airseeker. It's been a year since this request was made, so yeah feel free to close it.

**Comment by PrenaamD** [comment]
Based on the comment above, I'll close it
