### ISSUE TITLE
Use of only if enabled"

### ISSUE THREAD

**Issue by wkande** [api3dao/old-api3-docs#960]
The use of "(only if enabled)" in the file `config.json` for Deployment Files can get confusing. The prefix to each field definition should be more consistent and focused on "required" or "optional".

Suggestions:
1. (required)
2. (required, if enabled)
3. (optional)

The second example usually refers to a sub key of a parent that often enables a feature. See the **[Heartbeat field](https://docs.api3.org/airnode/v0.8/reference/deployment-files/config-json.html#httpgateway)** as an example.

**Comment by vponline** [comment]
option 2. seems most clear and consistent with having required/optional for the other fields
