### ISSUE TITLE
Rename `stage` field in the configuration to `deploymentId`

### ISSUE THREAD

**Issue by amarthadan** [api3dao/old-api3-docs#967]
Documentation for https://github.com/api3dao/airnode/issues/1375

**Comment by wkande** [comment]
@amarthadan - Who is doing this change. I see we are doing the documentation tasks differently now so I am not sure of the process.

**Comment by amarthadan** [comment]
What do you mean? This will be done as part of https://github.com/api3dao/airnode/issues/1375 by whoever will be working on that. This is the corresponding documentation task for that. We've been doing it this way since we switched to the GH board.

**Comment by wkande** [comment]
Usually the task was not split in the past. But this works better I think. I do not see anyone assigned so I do not know which developer is working on this and who I should contact to see if I can help. Are you just waiting to the next weekly Wednesday meeting to assign these? I see @aTeoke has also added a few.

**Comment by amarthadan** [comment]
It was like this for the last, I don't know, two months? For example [this Airnode issue](https://github.com/api3dao/airnode/issues/1192) and corresponding [docs issue](https://github.com/api3dao/api3-docs/issues/823), or [this Airnode issue](https://github.com/api3dao/airnode/issues/1205) and corresponding [docs issue](https://github.com/api3dao/api3-docs/issues/851). We've discussed it here https://github.com/api3dao/airnode/issues/1235.

But just to make it clear, the flow should be like this:
When there's an Airnode issue that needs documentation we assign the `needs documentation` label to it which triggers our automation and creates a corresponding issue in the docs repo. These two issues should be done by the same person unless stated otherwise (somebody else tagged in the comments or some such). So, if there are documentation issues that have corresponding Airnode issues (you can see that in the description) it's okay for them to not have anybody assigned, somebody will be assigned either on the planning call or somebody will take both from the TODO column.
Does it make sense?

**Comment by wkande** [comment]
@aTeoke and @amarthadan 

To-date nothing has been done on this issue, I think. The docs still use the field `stage` in both `v0.9` and `v0.10`. Did this not happen? If it was changed can the developer follow-up with the changes to the docs or at least educate me on the change (in detail) so I can help?

**Comment by amarthadan** [comment]
We've decided against it in the end. So, it wasn't implemented. The main issue was closed but the documentation one was forgotten. Sorry about that. Closing.
