### ISSUE TITLE
Change stage name/region for the tutorials

### ISSUE THREAD

**Issue by wkande** [api3dao/old-api3-docs#968]
Stage names for the tutorials currently are set to `dev`. For GCP many are having issues related to the stage name and need to change it to get a GCP deployment to work. This seems to be the case with the tutorials as well. They have been deployed by readers many times as `dev` to GCP and after a while they give a `storage.bucket` error. It may be related to the fact that the tutorial for GCP was including a zone in the region.

AWS: tutorial-aws
GCP: tutorial-gcp
Container: tutorial-container

**Comment by wkande** [comment]
@kolenic-martin - This was focused on the GCP tutorial for the most part. I have run the GCP tutorial many times today with `stage="tutorial-gcp"` and it seems fine. If you want to try it please do. Otherwise it can be moved to the done column.

**Comment by martinkolenic** [comment]
Hi, I've given all three tutorials a quick run and they all seem to be working smoothly. Setting a random stage name seems to be okay for both AWS and GCP as well.
