### ISSUE TITLE
"Introduction" and "Why use Airnode" texts blended in Why use Airnode? part of docs

### ISSUE THREAD

**Issue by metobom** [api3dao/old-api3-docs#982]
Link: https://docs.api3.org/airnode/v0.7/introduction/why-use-airnode.html
Google Chrome version: 103.0.5060.134 (Official Build) (64-bit)
Firefox version: 103.0 (64-bit)

![image](https://user-images.githubusercontent.com/46991761/185582284-298f40e9-3a7a-4469-bff6-44f1e0272e81.png)

**Comment by wkande** [comment]
@metobom Thanks for the catch, am fixing this now.

**Comment by wkande** [comment]
There is an extras termination to the TitleSpan element:
`<TitleSpan>{{$frontmatter.folder}}</TitleSpan>>`

**Comment by wkande** [comment]
PR: https://github.com/api3dao/api3-docs/pull/983
