### ISSUE TITLE
requestId-keyed per-endpoint caching

### ISSUE THREAD

**Issue by amarthadan** [api3dao/old-api3-docs#999]
Documentation for https://github.com/api3dao/airnode/issues/1190

**Comment by martinkolenic** [comment]
Hi @wkande, I cannot find any docs preview for this, nor can I find a relevant section that would include this - could you point me to it please? It might be just me.  Thanks.

**Comment by wkande** [comment]
@kolenic-martin - I merged the PR, probably got ahead of things. It is a simple change made by Derek. You can see it **[here](https://docs.api3.org/airnode/v0.8/reference/deployment-files/config-json.html#rrp-n-cacheresponses)**.

**Comment by martinkolenic** [comment]
Thanks, Warren. This looks fine to me, I'll move it to Done.
